// Precomputed prediction lookup — no server required.
//
// The JSON was generated by src/Rcode/precompute_predictions.R using the
// trained tidymodels workflow (final_rf_model_workflow.rds). Keys are:
//   {routeId}_{direction}_{season}_{daytype}_{tempF}_{precipPct}_{hour}
// e.g. "ER_SB_WINTER_WEEKDAY_65_0_8"
//
// To switch back to a live API (e.g. R Plumber hosted on Render/Railway):
//   1. Remove the loadCache() call from AppShell.vue onMounted
//   2. Restore the fetchPrediction() calls in handleSystemSubmit and onHourSelected
//   3. Update the API URL in fetchPrediction from localhost:8000 to your hosted URL

type PredictionResult = { delay_probability: number; risk_level: string }

let cache: Record<string, PredictionResult> | null = null

export async function loadCache(): Promise<void> {
  if (cache) return

  // Try base-prefixed path first (correct for GitHub Pages production).
  // Fall back to root path for Astro dev server, which may not apply the
  // base prefix to public/ assets depending on the version.
  const base = (import.meta.env.BASE_URL ?? '/').replace(/\/?$/, '/')
  const candidates = [
    `${base}predictions_precomputed.json`,
    `/predictions_precomputed.json`,
  ]

  for (const url of candidates) {
    try {
      const res = await fetch(url)
      console.log(`[predictionCache] ${url} → ${res.status} (${res.headers.get('content-type')})`)
      if (!res.ok) continue
      cache = await res.json()
      console.log(`[predictionCache] Loaded from ${url}`)
      return
    } catch (err) {
      console.warn(`[predictionCache] Failed at ${url}:`, err)
    }
  }

  console.error('[predictionCache] Could not load predictions_precomputed.json — predictions will return defaults.')
}

function snapTemp(tempF: number): number {
  return Math.round(Math.max(-20, Math.min(120, tempF)) / 5) * 5
}

function snapPrecip(pct: number): number {
  const bins = [0, 25, 50, 75, 100]
  return bins.reduce((prev, curr) =>
    Math.abs(curr - pct) < Math.abs(prev - pct) ? curr : prev
  )
}

export function lookupPrediction(
  routeId: string,
  direction: string,
  season: string,
  daytype: string,
  tempF: number,
  precipPct: number,
  hour: number
): PredictionResult {
  const key = `${routeId}_${direction}_${season}_${daytype}_${snapTemp(tempF)}_${snapPrecip(precipPct)}_${hour}`
  return cache?.[key] ?? { delay_probability: 0, risk_level: 'low' }
}
