{
  "hash": "96ef54a5603fe7031422443031fa0eff",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Analyzing and Predicting Delays for the NYC Ferry System\"\nsubtitle: \"2026 MUSA Practicum Project Supporting the NYC Economic Development Corportation\"\nauthors: \"Yiming 'Ming' Cao, Sujan Kakumanu, Tyler Maynard, Guangze 'Simon' Sun\"   \nformat:\n  html:\n    number-sections: true\n    code-fold: true\nexecute:\n  cache: true\n---\n\n::: {.d-flex .gap-2 .mb-4}\n[Launch our Application ↗](https://sujankakumanu.com/musa-8010-nycedc/){.btn .btn-primary .btn-sm target=\"_blank\"}\n[Go to the MUSA Practicum Page ↗](https://pennmusa.github.io/MUSA_801.io/){.btn .btn-primary .btn-sm target=\"_blank\"}\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Set options\noptions(scipen = 999, dplyr.summarise.inform = FALSE)\n\n# Packages\nif(!require(pacman)){install.packages(\"pacman\"); library(pacman, quietly = T)}\np_load(tidyverse, sf, viridis, lubridate, kableExtra, gridExtra, ggthemes, ggspatial, leaflet, spatstat, spdep, htmlwidgets, concaveman, patchwork, yardstick, arrow, broom, car, scales)\n```\n:::\n\n\n# Use Case\n\nNYC Ferry launched on May 1st, 2017 with a broad goal: connect underserved communities, complement existing transit, and support growing\nneighborhoods. That mission is reflected in how the system is designed — single-seat rides are possible between communities as far apart as   \nthe Bronx and the Rockaways. Since launch, the system has crossed 50 million riders and today spans 5 routes operated by 38 custom-built\nvessels across New York Harbor.                                                                                                               \n                \nThis project was done in partnership with the NYC Economic Development Corporation, the operator of NYC Ferry, to support on-time performance through  \nbetter operational forecasting. The use case centers on an operational manager who needs to allocate resources — upland agents, sweep boats,\nvessel assignments — ahead of anticipated delays.                                                                                             \n                \nThis breaks down into two key deliverables. First, an associative model exploring the historical contributing factors to delays between       \nlandings. Second, a predictive model that estimates the probability of an excessive delay (>10 minutes) between landings up to 48 hours ahead\nof a scheduled departure. The latter feeds into a web-based application designed for operational use. \n\n\n# Exploratory Data Analysis\n\n## Ridership and Trip Data\n**By: Guangze 'Simon' Sun and Yiming 'Ming' Cao**\n\n**Definition of Delay**\n\n*Arrival Time Variance (minutes):* Actual Arrival − Scheduled Arrival\n\n**Thresholds:**\n\n- **Delayed:** > 5 minutes\n- **Excessively delayed:** > 10 minutes\n\n**Rationale:** Based on NYC Ferry operational definitions. The >5 minute threshold is used for stop-level late-rate analysis throughout this section, reflecting stable classification with less noise than stricter cutoffs.\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntz_local <- \"America/New_York\"\n\nridership_files <- c(\n  \"../exploratory_code/ridership_eda/NYCF_ridership_details_2024.01_06.csv\",\n  \"../exploratory_code/ridership_eda/NYCF_ridership_details_2024.07_12.csv\",\n  \"../exploratory_code/ridership_eda/NYCF_ridership_details_2025.01_06.csv\"\n)\nstop_files <- c(\n  \"../exploratory_code/ridership_eda/NYCF_stop_data_2024.csv\",\n  \"../exploratory_code/ridership_eda/NYCF_stop_data_2025.01_06.csv\"\n)\n```\n:::\n\n\n### Overview\n\n#### Scope & sample definition\n\nThis notebook performs exploratory data analysis (EDA) on compiled NYC Ferry stop-level operations data.\n\nAll downstream analysis uses records from 2024-01-01 to 2025-06-30 (inclusive), and excludes 2024-04-25 for route `SB` due to a known schedule mismatch issue. Passenger activity is measured using `boarding_wake` and `alightings_wake` throughout.\n\n#### What this notebook produces\n\nThe notebook constructs a cleaned stop-level table, derives operational and reliability metrics (dwell, segment \"water time,\" delay, and late/early flags), and generates summary tables and plots across routes, months, and hours.\n\nThe final analysis sample is stored as `dat` (stop-level), which is also the only dataset exported at the end for downstream modeling and reporting.\n\n### Data Preparation\n\n#### Import Data\n\nThe following code loads the compiled stop-level dataset and the ridership details dataset. Ridership details are used only to obtain vessel capacity for computing load factor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstandardize_cols_ridership <- function(df) {\n  nm <- names(df)\n  nm <- ifelse(nm == \"Original_On\",  \"Original_ON\",  nm)\n  nm <- ifelse(nm == \"Original_Off\", \"Original_OFF\", nm)\n  nm <- ifelse(nm == \"WheelChair_On\",  \"WheelChair_ON\",  nm)\n  nm <- ifelse(nm == \"WheelChair_Off\", \"WheelChair_OFF\", nm)\n  names(df) <- nm\n  df\n}\n\nridership <- purrr::map_dfr(\n  ridership_files,\n  ~ readr::read_csv(.x, show_col_types = FALSE) %>%\n    standardize_cols_ridership()\n)\n\nstops <- purrr::map_dfr(\n  stop_files,\n  ~ readr::read_csv(.x, show_col_types = FALSE)\n)\n\nglimpse(ridership)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 961,890\nColumns: 15\n$ Date1           <chr> \"1/1/2024\", \"1/1/2024\", \"1/1/2024\", \"1/1/2024\", \"1/1/2…\n$ Route           <chr> \"ER\", \"ER\", \"ER\", \"ER\", \"ER\", \"ER\", \"ER\", \"ER\", \"ER\", …\n$ Direction       <chr> \"NB\", \"NB\", \"NB\", \"NB\", \"NB\", \"NB\", \"NB\", \"SB\", \"SB\", …\n$ Trip_Pattern    <chr> \"er_p11_gp_hps\", \"er_p11_gp_hps\", \"er_p11_gp_hps\", \"er…\n$ Trip_ID         <dbl> 1101, 1101, 1101, 1101, 1101, 1101, 1101, 1102, 1102, …\n$ Vessel_Id       <chr> \"H201\", \"H201\", \"H201\", \"H201\", \"H201\", \"H201\", \"H201\"…\n$ Vessel_Capacity <dbl> 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150,…\n$ Stop            <chr> \"Hunters Point South\", \"Wall St/Pier 11\", \"Dumbo/Fulto…\n$ Stop_Sequence   <dbl> NA, 1, 2, 3, 4, 5, 6, NA, 1, 2, 3, 4, 5, 6, NA, 1, 2, …\n$ Departure_Time  <time> 10:53:00, 10:05:00, 10:13:00, 10:25:00, 10:33:00, 10:…\n$ Original_ON     <dbl> 0, 8, 3, 1, 10, 16, 0, 0, 25, 37, 14, 13, 14, 12, 0, 2…\n$ Original_OFF    <dbl> 0, 0, 3, 2, 2, 4, 27, 35, 0, 13, 2, 15, 6, 44, 15, 0, …\n$ Left_Behind     <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…\n$ WheelChair_ON   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n$ WheelChair_OFF  <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …\n```\n\n\n:::\n\n```{.r .cell-code}\nglimpse(stops)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 753,951\nColumns: 27\n$ Row_Number             <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, …\n$ `Sort Key`             <chr> \"2024-01-011101ER  1\", \"2024-01-011101ER2\", \"20…\n$ vehicle_id             <chr> \"H201\", \"H201\", \"H201\", \"H201\", \"H201\", \"H201\",…\n$ trip_date              <chr> \"1/1/2024\", \"1/1/2024\", \"1/1/2024\", \"1/1/2024\",…\n$ trip_no                <dbl> 1101, 1101, 1101, 1101, 1101, 1101, 1101, 1102,…\n$ `Block Id`             <dbl> 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,…\n$ route_no               <chr> \"ER\", \"ER\", \"ER\", \"ER\", \"ER\", \"ER\", \"ER\", \"ER\",…\n$ route_direction        <chr> \"NB\", \"NB\", \"NB\", \"NB\", \"NB\", \"NB\", \"NB\", \"SB\",…\n$ route_pattern          <chr> \"er_p11_gp_hps\", \"er_p11_gp_hps\", \"er_p11_gp_hp…\n$ route_name             <chr> \"East River\", \"East River\", \"East River\", \"East…\n$ stop_name              <chr> \"Wall St/Pier 11\", \"Dumbo/Fulton Ferry\", \"South…\n$ scheduled_departure_dt <chr> \"1/1/2024 10:05\", \"1/1/2024 10:13\", \"1/1/2024 1…\n$ scheduled_arrival_dt   <chr> NA, \"1/1/2024 10:13\", \"1/1/2024 10:25\", \"1/1/20…\n$ actual_arrival_dt      <chr> NA, \"1/1/2024 10:10\", \"1/1/2024 10:24\", \"1/1/20…\n$ actual_departure_dt    <chr> \"1/1/2024 10:06\", \"1/1/2024 10:15\", \"1/1/2024 1…\n$ `Stop Sequence`        <dbl> 0, 1, 2, 3, 4, 5, 6, 2, 4, 5, 0, 1, 3, 6, 0, 5,…\n$ boarding_wake          <dbl> 8, 3, 1, 10, 16, 0, 0, 14, 14, 12, 25, 37, 13, …\n$ alightings_wake        <dbl> 0, 3, 2, 2, 4, 27, 0, 2, 6, 44, 0, 13, 15, 35, …\n$ alightings             <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ boardings              <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ lbr                    <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ `Dwell Time`           <time> 00:04:49, 00:02:35, 00:03:06, 00:03:25, 00:03:…\n$ dept_variance_flag     <chr> \"On_Time\", \"On_Time\", \"On_Time\", \"On_Time\", \"On…\n$ DepartureTimeVariance  <time> 00:01:16, 00:02:10, 00:02:06, 00:03:26, 00:04:…\n$ ArrivalTimeVariance    <time>       NA, 00:02:39, 00:00:29, 00:00:20, 00:00:…\n$ stop_id                <dbl> 87, 20, 8, 19, 18, 17, 4, 18, 8, 20, 4, 17, 19,…\n$ ...27                  <lgl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n```\n\n\n:::\n:::\n\n\n#### Clean stops & build basic features\n\nThis step standardizes key fields and column names, cleans `Sort Key`, derives weekday/weekend indicators, and computes an onboard count per stop using cumulative `boarding_wake` minus `alightings_wake` within each trip ordered by `Stop_Sequence`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstops <- stops %>%\n  mutate(`Sort Key` = str_replace_all(`Sort Key`, \"\\\\s+\", \"\")) %>%\n  rename_with(~ str_replace_all(.x, \"\\\\s+\", \"_\")) %>%\n  mutate(\n    trip_no = as.character(trip_no),\n    route_no = as.character(route_no),\n    route_direction = as.character(route_direction),\n    route_pattern = as.character(route_pattern),\n    stop_name = as.character(stop_name),\n    Stop_Sequence = as.integer(Stop_Sequence),\n    sort_key_adj = paste0(str_sub(Sort_Key, 1, -2), Stop_Sequence),\n    trip_date = mdy(trip_date),\n    weekday = wday(trip_date, label = TRUE, abbr = FALSE),\n    is_weekday = !wday(trip_date) %in% c(1, 7),\n    lbr = coalesce(lbr, 0)\n  ) %>%\n  group_by(trip_date, trip_no, route_no, route_direction) %>%\n  arrange(Stop_Sequence, .by_group = TRUE) %>%\n  mutate(\n    onboard = cumsum(coalesce(boarding_wake, 0)) - cumsum(coalesce(alightings_wake, 0))\n  ) %>%\n  ungroup() %>%\n  select(-any_of(c(\"Row_Number\", \"Sort_Key\", \"route_name\", \"...27\")))\n```\n:::\n\n\n#### Parse datetimes (NY local time)\n\nStop timestamps appear in different string formats across years. We parse both formats into POSIXct and keep them in America/New_York so that time-of-day patterns reflect local operations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparse_dt_nycf <- function(x, tz_local) {\n  x_chr <- as.character(x)\n  x_chr <- str_trim(na_if(x_chr, \"\"))\n\n  has_ampm <- str_detect(x_chr, regex(\"\\\\b(am|pm)\\\\b\", ignore_case = TRUE))\n  has_ampm[is.na(has_ampm)] <- FALSE\n\n  out <- as.POSIXct(rep(NA, length(x_chr)), tz = tz_local)\n\n  idx_2024 <- !has_ampm & !is.na(x_chr)\n  idx_2025 <-  has_ampm & !is.na(x_chr)\n\n  out[idx_2024] <- mdy_hm(x_chr[idx_2024], tz = tz_local, quiet = TRUE)\n  out[idx_2025] <- parse_date_time(\n    x_chr[idx_2025],\n    orders = c(\"mdY IMSp\", \"mdY IMp\"),\n    tz = tz_local,\n    quiet = TRUE\n  )\n\n  out\n}\n\nstops <- stops %>%\n  mutate(\n    scheduled_arrival_dt   = parse_dt_nycf(scheduled_arrival_dt, tz_local),\n    actual_arrival_dt      = parse_dt_nycf(actual_arrival_dt, tz_local),\n    scheduled_departure_dt = parse_dt_nycf(scheduled_departure_dt, tz_local),\n    actual_departure_dt    = parse_dt_nycf(actual_departure_dt, tz_local)\n  )\n```\n:::\n\n\n#### Enforce last-stop departure as missing\n\nFor each trip, the final stop should not have a meaningful departure timestamp. We explicitly set `actual_departure_dt` to missing for last stops to avoid incorrect dwell and segment calculations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstops <- stops %>%\n  arrange(trip_date, trip_no, route_no, route_direction, Stop_Sequence) %>%\n  mutate(\n    actual_departure_dt = if_else(\n      row_number() == n(),\n      as.POSIXct(NA, tz = tz_local),\n      actual_departure_dt\n    ),\n    .by = c(trip_date, trip_no, route_no, route_direction)\n  )\n```\n:::\n\n\n#### Compute delay / segment / dwell metrics\n\nWe compute arrival/departure delay relative to schedule, \"water travel\" time between consecutive stops (previous departure to current arrival), and dwell time at stops (arrival to departure). These derived metrics support distribution checks and late-rate analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstops <- stops %>%\n  select(-any_of(\"dept_variance_flag\")) %>%\n  mutate(\n    arr_diff = as.numeric(difftime(actual_arrival_dt, scheduled_arrival_dt, units = \"mins\")),\n    dep_diff = as.numeric(difftime(actual_departure_dt, scheduled_departure_dt, units = \"mins\"))\n  ) %>%\n  arrange(trip_date, trip_no, route_no, route_direction, Stop_Sequence) %>%\n  mutate(\n    sched_water_min = as.numeric(difftime(scheduled_arrival_dt, lag(scheduled_departure_dt), units = \"mins\")),\n    act_water_min   = as.numeric(difftime(actual_arrival_dt,    lag(actual_departure_dt),    units = \"mins\")),\n    water_diff      = act_water_min - sched_water_min,\n    .by = c(trip_date, trip_no, route_no, route_direction)\n  ) %>%\n  mutate(\n    act_dwell_min = as.numeric(difftime(actual_departure_dt, actual_arrival_dt, units = \"mins\"))\n  )\n```\n:::\n\n\n#### Define lateness / earliness flags\n\nWe define Late arrival as `arr_diff` > 5 minutes and Early departure as `dep_diff` < -1 minute. These thresholds are used consistently throughout the reliability summaries and plots.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstops <- stops %>%\n  mutate(\n    arr_status = case_when(\n      is.na(arr_diff) ~ NA_character_,\n      arr_diff > 5    ~ \"Late\",\n      TRUE            ~ \"Not_Late\"\n    ),\n    dep_status = case_when(\n      is.na(dep_diff) ~ NA_character_,\n      dep_diff < -1   ~ \"Early\",\n      TRUE            ~ \"Not_Early\"\n    )\n  )\n```\n:::\n\n\n#### Join vessel capacity and compute load factor\n\nWe join `Vessel_Capacity` using four keys (`trip_date`, `route_pattern`, `trip_no`, `stop_name`) and compute `load_factor = onboard / Vessel_Capacity`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nridership_capacity_lookup <- ridership %>%\n  transmute(\n    trip_date     = mdy(Date1),\n    route_pattern = as.character(Trip_Pattern),\n    trip_no       = as.character(Trip_ID),\n    stop_name     = as.character(Stop),\n    Vessel_Capacity\n  ) %>%\n  filter(!is.na(Vessel_Capacity)) %>%\n  distinct(trip_date, route_pattern, trip_no, stop_name, Vessel_Capacity)\n\nstops <- stops %>%\n  left_join(\n    ridership_capacity_lookup,\n    by = c(\n      \"trip_date\" = \"trip_date\",\n      \"route_pattern\" = \"route_pattern\",\n      \"trip_no\" = \"trip_no\",\n      \"stop_name\" = \"stop_name\"\n    )\n  ) %>%\n  mutate(load_factor = onboard / Vessel_Capacity)\n```\n:::\n\n\n#### Define analysis sample\n\nWe construct the final analysis table `dat` by applying the study period filter and removing the known problematic day/route subset. All EDA that follows is based on `dat` unless explicitly noted.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat0 <- stops %>%\n  filter(trip_date >= ymd(\"2024-01-01\"),\n         trip_date <= ymd(\"2025-06-30\"))\n\nremoved_0425_sb <- dat0 %>%\n  filter(trip_date == ymd(\"2024-04-25\") & route_no == \"SB\")\n\ndat <- dat0 %>%\n  filter(!(trip_date == ymd(\"2024-04-25\") & route_no == \"SB\"))\n\ntibble(\n  min_trip_date = min(dat$trip_date, na.rm = TRUE),\n  max_trip_date = max(dat$trip_date, na.rm = TRUE),\n  n_rows_in_range_before_drop = nrow(dat0),\n  n_rows_removed_2024_04_25_SB = nrow(removed_0425_sb),\n  n_rows_final = nrow(dat)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n  min_trip_date max_trip_date n_rows_in_range_before_drop n_rows_removed_2024_…¹\n  <date>        <date>                              <int>                  <int>\n1 2024-01-01    2025-06-30                         753951                    366\n# ℹ abbreviated name: ¹​n_rows_removed_2024_04_25_SB\n# ℹ 1 more variable: n_rows_final <int>\n```\n\n\n:::\n:::\n\n\n### EDA Tables\n\n#### Derived tables\n\nWe create two helper tables to support EDA at different aggregation levels:\n\n- `trip_tbl` summarizes one row per trip (useful for route/month/trip-start timing summaries).\n- `dist_dat` keeps stop-level records with convenience fields (e.g., stop_volume, nonnegative onboard/load factor) for distributions and late-rate calculations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrip_tbl <- dat %>%\n  mutate(trip_key = paste(trip_date, route_no, route_direction, trip_no, sep = \"|\")) %>%\n  group_by(trip_key, trip_date, route_no, route_direction) %>%\n  arrange(Stop_Sequence, .by_group = TRUE) %>%\n  summarise(\n    n_stops = n_distinct(stop_id),\n    trip_boardings  = sum(boarding_wake, na.rm = TRUE),\n    trip_alightings = sum(alightings_wake, na.rm = TRUE),\n    trip_total_events = sum(boarding_wake + alightings_wake, na.rm = TRUE),\n    trip_start_departure = first(actual_departure_dt),\n    is_weekday = first(is_weekday),\n    month = floor_date(first(trip_date), \"month\"),\n    .groups = \"drop\"\n  ) %>%\n  mutate(\n    day_type = if_else(is_weekday, \"Weekday\", \"Weekend\"),\n    dep_hour = hour(trip_start_departure)\n  )\n\ndist_dat <- dat %>%\n  mutate(\n    boarding_wake = coalesce(boarding_wake, 0),\n    alightings_wake = coalesce(alightings_wake, 0),\n    stop_volume = boarding_wake + alightings_wake,\n    dwell_min = act_dwell_min,\n    onboard_nonneg = pmax(onboard, 0),\n    load_factor_nonneg = onboard_nonneg / Vessel_Capacity\n  )\n```\n:::\n\n\n#### Route overview (Weekday vs Weekend)\n\nRoute-level summaries compare weekday and weekend patterns to distinguish commute-driven demand from leisure and discretionary travel. We report total trips, total boardings, and average boardings per trip by route.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroute_weekpart <- trip_tbl %>%\n  group_by(route_no, day_type) %>%\n  summarise(\n    total_trips = n(),\n    total_boardings = sum(trip_boardings, na.rm = TRUE),\n    .groups = \"drop\"\n  )\n\nroute_avg_weekpart <- trip_tbl %>%\n  group_by(route_no, day_type) %>%\n  summarise(\n    avg_boardings_per_trip = mean(trip_boardings, na.rm = TRUE),\n    n_trips = n(),\n    .groups = \"drop\"\n  )\n\nroute_summary_by_stops <- trip_tbl %>%\n  group_by(route_no, route_direction, n_stops) %>%\n  summarise(\n    n_trips = n(),\n    total_boardings = sum(trip_boardings, na.rm = TRUE),\n    avg_boardings_per_trip = total_boardings / n_trips,\n    .groups = \"drop\"\n  ) %>%\n  arrange(route_no, route_direction, n_stops)\n\nroute_weekpart %>% arrange(desc(total_boardings))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 16 × 4\n   route_no day_type total_trips total_boardings\n   <chr>    <chr>          <int>           <dbl>\n 1 ER       Weekday        24863         2730172\n 2 AS       Weekday        15047         1533359\n 3 ER       Weekend         7541         1302644\n 4 SV       Weekday        14933          919075\n 5 SB       Weekday        18874          709380\n 6 AS       Weekend         4732          692798\n 7 RW       Weekday        11950          655102\n 8 SG       Weekday        19744          653251\n 9 SB       Weekend         5189          482218\n10 RW       Weekend         4582          334244\n11 SV       Weekend         4617          326769\n12 SG       Weekend         6534          253360\n13 GI       Weekend         1292           49853\n14 GI       Weekday          444           22963\n15 RR       Weekend           84            8951\n16 RR       Weekday            6             900\n```\n\n\n:::\n\n```{.r .cell-code}\nroute_summary_by_stops\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 28 × 6\n   route_no route_direction n_stops n_trips total_boardings\n   <chr>    <chr>             <int>   <int>           <dbl>\n 1 AS       NB                    7    9705         1014103\n 2 AS       SB                    7   10074         1212054\n 3 ER       NB                    7   16037         2012111\n 4 ER       SB                    7   16367         2020705\n 5 GI       NB                    2     897           30485\n 6 GI       SB                    2     839           42331\n 7 RR       NB                    3      45            4085\n 8 RR       SB                    3      45            5766\n 9 RW       NB                    3    8511          505836\n10 RW       SB                    3    8021          483510\n# ℹ 18 more rows\n# ℹ 1 more variable: avg_boardings_per_trip <dbl>\n```\n\n\n:::\n:::\n\n\n#### Stop totals\n\nStop totals aggregate boardings and alightings across the analysis period to identify the highest-activity stops. These rankings help interpret which terminals or transfer points dominate system usage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstop_totals <- dat %>%\n  group_by(stop_id, stop_name) %>%\n  summarise(\n    total_boardings = sum(boarding_wake, na.rm = TRUE),\n    total_alightings = sum(alightings_wake, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  arrange(desc(total_boardings))\n\nstop_totals\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 25 × 4\n   stop_id stop_name           total_boardings total_alightings\n     <dbl> <chr>                         <dbl>            <dbl>\n 1      87 Wall St/Pier 11             2163272          2562409\n 2      17 East 34th Street            1404634          1566502\n 3      20 Dumbo/Fulton Ferry           990583           884817\n 4      19 North Williamsburg           560850           520351\n 5     113 East 90th St                 533628           489918\n 6      88 Rockaway                     438062           435374\n 7      18 Greenpoint                   431993           388197\n 8       4 Hunters Point South          417259           397537\n 9      89 Astoria                      414117           342461\n10     137 St. George                   387301           331679\n# ℹ 15 more rows\n```\n\n\n:::\n:::\n\n\n#### Monthly patterns\n\nMonthly summaries provide a simple view of seasonality and demand shifts over time. We summarize trips and ridership by month, split by weekday vs weekend, and also compute average boardings per trip.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonthly_weekpart <- trip_tbl %>%\n  filter(month >= ymd(\"2024-01-01\"), month <= ymd(\"2025-06-01\")) %>%\n  group_by(month, day_type) %>%\n  summarise(\n    total_trips = n(),\n    total_boardings = sum(trip_boardings, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  arrange(month, day_type)\n\nmonthly_avg_weekpart <- trip_tbl %>%\n  filter(month >= ymd(\"2024-01-01\"), month <= ymd(\"2025-06-01\")) %>%\n  group_by(month, day_type) %>%\n  summarise(\n    avg_boardings_per_trip = mean(trip_boardings, na.rm = TRUE),\n    n_trips = n(),\n    .groups = \"drop\"\n  ) %>%\n  arrange(month, day_type)\n\nmonthly_weekpart\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 36 × 4\n   month      day_type total_trips total_boardings\n   <date>     <chr>          <int>           <dbl>\n 1 2024-01-01 Weekday         5912          254505\n 2 2024-01-01 Weekend         1176           49751\n 3 2024-02-01 Weekday         5547          250456\n 4 2024-02-01 Weekend         1176           76538\n 5 2024-03-01 Weekday         5671          307774\n 6 2024-03-01 Weekend         1610          142854\n 7 2024-04-01 Weekday         6015          392494\n 8 2024-04-01 Weekend         1799          179812\n 9 2024-05-01 Weekday         6290          485912\n10 2024-05-01 Weekend         1982          233380\n# ℹ 26 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\nmonthly_avg_weekpart\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 36 × 4\n   month      day_type avg_boardings_per_trip n_trips\n   <date>     <chr>                     <dbl>   <int>\n 1 2024-01-01 Weekday                    43.0    5912\n 2 2024-01-01 Weekend                    42.3    1176\n 3 2024-02-01 Weekday                    45.2    5547\n 4 2024-02-01 Weekend                    65.1    1176\n 5 2024-03-01 Weekday                    54.3    5671\n 6 2024-03-01 Weekend                    88.7    1610\n 7 2024-04-01 Weekday                    65.3    6015\n 8 2024-04-01 Weekend                   100.0    1799\n 9 2024-05-01 Weekday                    77.3    6290\n10 2024-05-01 Weekend                   118.     1982\n# ℹ 26 more rows\n```\n\n\n:::\n:::\n\n\n#### Time-of-day patterns\n\nHourly patterns are summarized in two ways: (1) trip-level departure hour, and (2) stop-level departure hour. This helps distinguish \"when trips start\" from \"when stop activity occurs\" across the day.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhour_weekpart <- trip_tbl %>%\n  filter(!is.na(dep_hour)) %>%\n  mutate(dep_hour = as.integer(dep_hour)) %>%\n  group_by(dep_hour, day_type) %>%\n  summarise(\n    total_boardings = sum(trip_boardings, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  arrange(dep_hour, day_type)\n\nhour_breaks <- sort(unique(hour_weekpart$dep_hour))\n\nstop_hour_weekpart <- dat %>%\n  filter(!is.na(actual_departure_dt)) %>%\n  mutate(\n    dep_hour = hour(actual_departure_dt),\n    day_type = if_else(is_weekday, \"Weekday\", \"Weekend\")\n  ) %>%\n  filter(!is.na(dep_hour)) %>%\n  group_by(dep_hour, day_type) %>%\n  summarise(\n    n_stop_departures = n(),\n    total_boardings = sum(boarding_wake, na.rm = TRUE),\n    avg_boardings_per_stop = total_boardings / n_stop_departures,\n    .groups = \"drop\"\n  ) %>%\n  arrange(dep_hour, day_type)\n\nstop_hour_breaks <- sort(unique(stop_hour_weekpart$dep_hour))\n\nstop_hour_weekpart\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 35 × 5\n   dep_hour day_type n_stop_departures total_boardings avg_boardings_per_stop\n      <int> <chr>                <int>           <dbl>                  <dbl>\n 1        5 Weekday               3952           36452                   9.22\n 2        6 Weekday              20969          150588                   7.18\n 3        7 Weekday              34867          481665                  13.8 \n 4        7 Weekend                226            2073                   9.17\n 5        8 Weekday              35072          661987                  18.9 \n 6        8 Weekend               2531           18147                   7.17\n 7        9 Weekday              36180          405600                  11.2 \n 8        9 Weekend               8745          107551                  12.3 \n 9       10 Weekday              29757          310091                  10.4 \n10       10 Weekend               9459          161616                  17.1 \n# ℹ 25 more rows\n```\n\n\n:::\n:::\n\n\n#### Late rate patterns\n\nLate rate is the primary reliability outcome in this EDA. We report overall shares of late arrivals and early departures, then summarize late rates by route, month, weekday vs weekend, and departure hour.\n\n\n::: {.cell}\n\n```{.r .cell-code}\narr_status_tab <- dist_dat %>%\n  filter(!is.na(arr_status)) %>%\n  count(arr_status, name = \"n\") %>%\n  mutate(pct = n / sum(n)) %>%\n  arrange(desc(n))\n\ndep_status_tab <- dist_dat %>%\n  filter(!is.na(dep_status)) %>%\n  count(dep_status, name = \"n\") %>%\n  mutate(pct = n / sum(n)) %>%\n  arrange(desc(n))\n\narr_status_tab\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  arr_status      n    pct\n  <chr>       <int>  <dbl>\n1 Not_Late   558419 0.931 \n2 Late        41247 0.0688\n```\n\n\n:::\n\n```{.r .cell-code}\ndep_status_tab\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  dep_status      n     pct\n  <chr>       <int>   <dbl>\n1 Not_Early  599844 0.998  \n2 Early        1155 0.00192\n```\n\n\n:::\n\n```{.r .cell-code}\nlate_dat <- dist_dat %>%\n  filter(!is.na(arr_status)) %>%\n  mutate(\n    is_late = arr_status == \"Late\",\n    month = floor_date(trip_date, \"month\"),\n    day_type = if_else(is_weekday, \"Weekday\", \"Weekend\"),\n    dep_hour = hour(actual_departure_dt)\n  )\n\nlate_by_route <- late_dat %>%\n  group_by(route_no) %>%\n  summarise(n = n(), pct_late = mean(is_late), .groups = \"drop\") %>%\n  arrange(desc(pct_late))\n\nlate_by_month <- late_dat %>%\n  group_by(month, day_type) %>%\n  summarise(n = n(), pct_late = mean(is_late), .groups = \"drop\") %>%\n  arrange(month, day_type)\n\nlate_by_daytype <- late_dat %>%\n  group_by(day_type) %>%\n  summarise(n = n(), pct_late = mean(is_late), .groups = \"drop\")\n\nlate_by_hour <- late_dat %>%\n  filter(!is.na(dep_hour)) %>%\n  group_by(dep_hour, day_type) %>%\n  summarise(n = n(), pct_late = mean(is_late), .groups = \"drop\") %>%\n  arrange(dep_hour, day_type)\n\nlate_hour_breaks <- sort(unique(late_by_hour$dep_hour))\n\nlate_by_route %>% head(30)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 3\n  route_no      n pct_late\n  <chr>     <int>    <dbl>\n1 RW        31870   0.185 \n2 SV        95635   0.0900\n3 RR          172   0.0872\n4 GI         1622   0.0660\n5 SB       111056   0.0648\n6 ER       191089   0.0578\n7 AS       116669   0.0526\n8 SG        51553   0.0435\n```\n\n\n:::\n\n```{.r .cell-code}\nlate_by_month\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 36 × 4\n   month      day_type     n pct_late\n   <date>     <chr>    <int>    <dbl>\n 1 2024-01-01 Weekday  24647   0.0394\n 2 2024-01-01 Weekend   4960   0.0756\n 3 2024-02-01 Weekday  23016   0.0374\n 4 2024-02-01 Weekend   5052   0.0954\n 5 2024-03-01 Weekday  23804   0.0436\n 6 2024-03-01 Weekend   7033   0.152 \n 7 2024-04-01 Weekday  25555   0.0492\n 8 2024-04-01 Weekend   8033   0.0919\n 9 2024-05-01 Weekday  25981   0.0609\n10 2024-05-01 Weekend   8548   0.0930\n# ℹ 26 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\nlate_by_daytype\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  day_type      n pct_late\n  <chr>     <int>    <dbl>\n1 Weekday  451367   0.0607\n2 Weekend  148299   0.0934\n```\n\n\n:::\n\n```{.r .cell-code}\nlate_by_hour\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 34 × 4\n   dep_hour day_type     n pct_late\n      <int> <chr>    <int>    <dbl>\n 1        5 Weekday   2549   0.0118\n 2        6 Weekday  14253   0.0149\n 3        7 Weekday  25748   0.0116\n 4        8 Weekday  26783   0.0286\n 5        8 Weekend   1582   0.0107\n 6        9 Weekday  27496   0.0293\n 7        9 Weekend   6560   0.0194\n 8       10 Weekday  24007   0.0276\n 9       10 Weekend   6970   0.0191\n10       11 Weekday  18792   0.0188\n# ℹ 24 more rows\n```\n\n\n:::\n:::\n\n\n### EDA Figures\n\n#### Route-level figures\n\nThese figures visualize route-level differences in service volume and demand. Weekday vs weekend splits highlight routes that are more commute-oriented versus leisure-oriented.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(route_weekpart,\n       aes(x = reorder(route_no, total_boardings, FUN = sum),\n           y = total_boardings, fill = day_type)) +\n  geom_col(position = \"stack\") +\n  coord_flip() +\n  labs(x = \"Route\", y = \"Total boardings\", fill = NULL,\n       title = \"Total ridership by route (Weekday vs Weekend)\")\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\nTotal boardings are highest on East River (ER) and Astoria (AS).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(route_avg_weekpart,\n       aes(x = reorder(route_no, avg_boardings_per_trip, FUN = max),\n           y = avg_boardings_per_trip, fill = day_type)) +\n  geom_col(position = position_dodge(width = 0.8), width = 0.75) +\n  coord_flip() +\n  labs(x = \"Route\", y = \"Avg boardings per trip\", fill = NULL,\n       title = \"Average ridership per trip by route (Weekday vs Weekend)\")\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nAverage boardings per trip tend to be higher on weekends than weekdays. For the seasonal routes, weekday averages can appear high because weekday service days are holiday/peak-operation days.\n\n#### Monthly figures\n\nMonthly charts provide a high-level view of seasonality and temporal shifts in trips, total ridership, and average ridership per trip.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(monthly_weekpart, aes(x = month, y = total_boardings, fill = day_type)) +\n  geom_col(position = \"stack\") +\n  scale_x_date(date_breaks = \"1 month\", date_labels = \"%Y-%m\") +\n  labs(x = NULL, y = \"Total boardings\", fill = NULL,\n       title = \"Monthly ridership (Weekday vs Weekend)\") +\n  theme(axis.text.x = element_text(angle = 60, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\nRidership varies much more strongly by season than trips do, especially on weekends.\n\n\n#### Time-of-day figures\n\nTime-of-day plots show how ridership and activity vary across hours.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(hour_weekpart, aes(x = dep_hour, y = total_boardings, fill = day_type)) +\n  geom_col(position = \"stack\") +\n  scale_x_continuous(breaks = hour_breaks) +\n  scale_y_continuous(labels = scales::comma) +\n  labs(title = \"Total ridership by trip departure hour (Weekday vs Weekend)\",\n       x = \"Departure hour\", y = \"Total boardings\", fill = NULL)\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nOn weekdays, stop activity shows morning and evening peaks consistent with commuting patterns. On weekends, higher activity is concentrated from midday through early evening.\n\n#### Distributions\n\nDistribution plots are used as diagnostics to understand skew, outliers, and reasonable ranges for modeling. These figures are intended to guide feature engineering and robustness checks.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(dist_dat %>% filter(!is.na(stop_volume), stop_volume >= 0, stop_volume <= 350),\n       aes(x = stop_volume)) +\n  geom_histogram(bins = 50) +\n  scale_y_continuous(labels = scales::comma) +\n  labs(title = \"Distribution of stop activity (board_wake + alight_wake)\",\n       x = \"stop_volume\", y = \"Count\")\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nStop activity is highly right-skewed: most stops have relatively low combined boardings/alightings, while a small number of high-activity stops drive the upper tail. The majority of observations are below ~50 per stop.\n\n\n#### Late-rate figures\n\nThese figures visualize how late rate varies across routes, months, and hours.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(late_by_route, aes(x = reorder(route_no, pct_late), y = pct_late)) +\n  geom_col() +\n  coord_flip() +\n  scale_y_continuous(labels = scales::percent_format()) +\n  labs(title = \"Late rate by route\", x = \"Route\", y = \"Share Late (arr_status)\")\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\nRockaway (RW) has the highest late rate by a wide margin relative to other routes. It is the longest route and more exposed to high seasonal peaks and variable marine conditions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(late_by_month, aes(x = month, y = pct_late, color = day_type)) +\n  geom_line() +\n  geom_point() +\n  scale_x_date(date_breaks = \"1 month\", date_labels = \"%Y-%m\") +\n  scale_y_continuous(labels = scales::percent_format()) +\n  labs(title = \"Late rate by month\", x = NULL, y = \"Share Late\", color = NULL) +\n  theme(axis.text.x = element_text(angle = 60, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\nLate rates are generally higher in summer than winter, and higher on weekends than weekdays.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(late_by_hour, aes(x = dep_hour, y = pct_late, color = day_type)) +\n  geom_line() +\n  geom_point() +\n  scale_x_continuous(breaks = late_hour_breaks) +\n  scale_y_continuous(labels = scales::percent_format()) +\n  labs(title = \"Late rate by stop departure hour\", x = \"Hour\", y = \"Share Late\", color = NULL)\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nLate rates tend to peak in the afternoon.\n\n#### Late propagation proxy figures\n\nTo proxy delay propagation along a trip, we relate a stop's lateness to conditions at the previous stop. We show late rates binned by previous-stop dwell time and by previous-stop passenger activity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprev_dat <- dist_dat %>%\n  arrange(trip_date, route_no, route_direction, trip_no, Stop_Sequence) %>%\n  group_by(trip_date, route_no, route_direction, trip_no) %>%\n  mutate(\n    prev_dwell_min   = lag(dwell_min),\n    prev_stop_volume = lag(stop_volume)\n  ) %>%\n  ungroup() %>%\n  filter(!is.na(arr_status),\n         !is.na(prev_dwell_min), prev_dwell_min >= 0, prev_dwell_min <= 60,\n         !is.na(prev_stop_volume), prev_stop_volume >= 0)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprev_dwell_late_tbl <- prev_dat %>%\n  mutate(\n    prev_dwell_bin = cut(prev_dwell_min,\n                         breaks = c(0, 1, 2, 3, 5, 8, 12, 16, Inf),\n                         include.lowest = TRUE)\n  ) %>%\n  group_by(prev_dwell_bin) %>%\n  summarise(n = n(), pct_late = mean(arr_status == \"Late\", na.rm = TRUE), .groups = \"drop\")\n\nprev_dwell_late_tbl\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 3\n  prev_dwell_bin      n pct_late\n  <fct>           <int>    <dbl>\n1 [0,1]            2041   0.111 \n2 (1,2]           26936   0.108 \n3 (2,3]          117033   0.0843\n4 (3,5]          239932   0.0633\n5 (5,8]           68604   0.0814\n6 (8,12]           4537   0.232 \n7 (12,16]            98   0.612 \n8 (16,Inf]           46   0.978 \n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(prev_dwell_late_tbl, aes(x = prev_dwell_bin, y = pct_late)) +\n  geom_col() +\n  geom_text(aes(label = paste0(\"n=\", scales::comma(n))), vjust = -0.3, size = 3) +\n  scale_y_continuous(labels = scales::percent_format(), expand = expansion(mult = c(0, 0.12))) +\n  labs(title = \"Late rate by previous-stop dwell time bin\",\n       x = \"Previous stop dwell time bin (min)\", y = \"Late rate (current stop)\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\nWithin typical dwell time ranges, the relationship between previous-stop dwell and current-stop late rate is relatively weak. Once previous-stop dwell becomes unusually long (e.g., > ~8 minutes), late rates increase sharply.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprev_vol_late_tbl <- prev_dat %>%\n  mutate(\n    prev_vol_bin = cut(prev_stop_volume,\n                       breaks = c(0, 10, 20, 30, 50, 100, 150, 200, Inf),\n                       include.lowest = TRUE)\n  ) %>%\n  group_by(prev_vol_bin) %>%\n  summarise(n = n(), pct_late = mean(arr_status == \"Late\", na.rm = TRUE), .groups = \"drop\")\n\nprev_vol_late_tbl\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 8 × 3\n  prev_vol_bin      n pct_late\n  <fct>         <int>    <dbl>\n1 [0,10]       134481   0.0540\n2 (10,20]      105747   0.0544\n3 (20,30]       71734   0.0677\n4 (30,50]       78063   0.0873\n5 (50,100]      56688   0.129 \n6 (100,150]     11025   0.220 \n7 (150,200]      1332   0.335 \n8 (200,Inf]       157   0.573 \n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(prev_vol_late_tbl, aes(x = prev_vol_bin, y = pct_late)) +\n  geom_col() +\n  geom_text(aes(label = paste0(\"n=\", scales::comma(n))), vjust = -0.3, size = 3) +\n  scale_y_continuous(labels = scales::percent_format(), expand = expansion(mult = c(0, 0.12))) +\n  labs(title = \"Late rate by previous-stop activity bin (board_wake + alight_wake)\",\n       x = \"Previous stop activity bin\", y = \"Late rate (current stop)\") +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\nWhen previous-stop activity is moderate, late rates change gradually; beyond higher activity levels (e.g., > ~50), late rates rise more noticeably.\n\nTaken together, these patterns suggest that delay is driven less by commuter peaks and more by high-demand recreational periods, particularly on routes serving waterfront leisure destinations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexport_dir <- \"../exploratory_code/ridership_eda\"\nreadr::write_csv(dat, file.path(export_dir, \"dat_stops_2024-01-01_2025-06-30_drop0425SB.csv.gz\"))\nsaveRDS(dat, file.path(export_dir, \"dat_stops_2024-01-01_2025-06-30_drop0425SB.rds\"))\n```\n:::\n\n\n### Operational Analysis\n**By: Guangze 'Simon' Sun and Yiming 'Ming' Cao**\n\nThis operational EDA complements the associative model by examining how ferry delay is recorded, decomposed, generated, and recovered. The four sections ask what issues are recorded in trip notes, how stop-level delay can be decomposed, where large delays are observed versus generated upstream, and whether inherited delay can be absorbed before the next trip begins.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrip_files <- c(\n  \"../exploratory_code/ridership_eda/NYCF_trip_data_2024.csv\",\n  \"../exploratory_code/ridership_eda/NYCF_trip_data_2025.01_06.csv\"\n)\ndecomp_file <- \"../exploratory_code/modeling/stop_level_arrival_decomposition_table_corrected_second_stop.csv\"\n\naccent       <- \"#1A9988\"\ngold         <- \"#F2C14E\"\ncoral        <- \"#D95F59\"\nblue         <- \"#7BA7C7\"\nmuted_palette <- c(\n  \"Inherited previous-trip delay\" = \"#1A9988\",\n  \"Carried within-trip delay\"     = \"#F2C14E\",\n  \"Upstream landside delay\"       = \"#7BA7C7\",\n  \"Upstream waterside delay\"      = \"#D95F59\"\n)\nplot_theme <- theme_minimal(base_size = 14) +\n  theme(\n    plot.title    = element_text(face = \"bold\", size = 17),\n    panel.grid.minor = element_blank(),\n    legend.title  = element_blank(),\n    axis.text     = element_text(color = \"#333333\")\n  )\n\nfmt_pct <- function(x) percent(x, accuracy = 0.1)\nclean_kable <- function(x, caption = NULL, align = NULL) {\n  if (is.null(align)) {\n    align <- paste0(if_else(map_lgl(x, is.character), \"l\", \"r\"), collapse = \"\")\n  }\n  kable(x, caption = caption, align = align)\n}\n```\n:::\n\n\n#### Text Analysis\n\nTrip notes were extracted from raw NYC Ferry trip-level files and parsed into standardized categories. One trip can have multiple categories, so category shares are presence rates rather than mutually exclusive percentages. Results are descriptive associations, not causal effects.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nparse_note_segments <- function(trip_uid, note_text) {\n  note_text <- ifelse(is.na(note_text), \"\", note_text)\n  if (str_trim(note_text) == \"\") return(tibble(trip_uid = integer(), category = character(), description = character()))\n  matches <- str_match_all(note_text, \"\\\\[(\\\\d+)\\\\]\\\\s*([^:\\\\[]+):\\\\s*([^\\\\[]*)\")[[1]]\n  if (nrow(matches) == 0) return(tibble(trip_uid = trip_uid, category = \"Unparsed\", description = note_text))\n  tibble(trip_uid = trip_uid, category = matches[, 3], description = matches[, 4])\n}\n\nclean_category <- function(x) {\n  out <- str_squish(x) %>% str_replace_all(\"\\\\s+\", \" \") %>% str_to_title()\n  dplyr::recode(out, \"Uscg Restriction\" = \"USCG Restriction\", \"Nyc Ferry\" = \"NYC Ferry\", \"Ny Waterway\" = \"NY Waterway\", .default = out)\n}\n\nraw_trips <- map_dfr(trip_files, ~ read_csv(.x, show_col_types = FALSE) %>% mutate(source_file = basename(.x))) %>%\n  select(-matches(\"^\\\\.\\\\.\\\\.\"))\n\ntrips <- raw_trips %>%\n  mutate(\n    trip_uid = row_number(),\n    route = if (\"route_no\" %in% names(.)) route_no else NA_character_,\n    service_date = if (\"trip_date\" %in% names(.)) mdy(trip_date) else as.Date(NA),\n    note_text = coalesce(notes, \"\"),\n    scheduled_arrival_ts = mdy_hm(scheduled_arrival_dt, quiet = TRUE),\n    actual_arrival_ts    = mdy_hm(actual_arrival_dt,    quiet = TRUE),\n    arrival_delay_min_raw = as.numeric(difftime(actual_arrival_ts, scheduled_arrival_ts, units = \"mins\")),\n    status_text = str_squish(str_c(coalesce(trip_status, \"\"), coalesce(trip_status_actual, \"\"), sep = \" | \")),\n    cancelled            = str_detect(str_to_lower(status_text), \"trip not completed|cancel\") | coalesce(`(16) Trip Cancelled`, FALSE),\n    partial_completion   = str_detect(str_to_lower(status_text), \"partial\") | coalesce(`(17) Partially Completed`, FALSE),\n    cancel_or_partial_completion = cancelled | partial_completion,\n    completed_trip = !cancel_or_partial_completion & (str_detect(str_to_lower(status_text), \"completed\") | coalesce(`(10)  Completed`, FALSE)),\n    valid_delay         = completed_trip & !is.na(arrival_delay_min_raw),\n    delayed_5           = valid_delay & arrival_delay_min_raw > 5,\n    excessive_delay_10  = valid_delay & arrival_delay_min_raw > 10\n  )\n\nnote_segments <- map2_dfr(trips$trip_uid, trips$note_text, parse_note_segments) %>%\n  mutate(category = clean_category(category), description = str_squish(description)) %>%\n  filter(!is.na(category), category != \"\")\n\ntrip_category <- note_segments %>%\n  distinct(trip_uid, category) %>%\n  left_join(trips %>% select(trip_uid, route, service_date, note_text, arrival_delay_min_raw,\n                             delayed_5, excessive_delay_10, cancel_or_partial_completion), by = \"trip_uid\") %>%\n  filter(category != \"Completed\")\n\ncategory_presence <- trip_category %>%\n  group_by(category) %>%\n  summarise(\n    n_trips_with_category = n_distinct(trip_uid),\n    share_all_trips = n_trips_with_category / nrow(trips),\n    share_among_delayed_5 = n_distinct(trip_uid[delayed_5]) / sum(trips$delayed_5, na.rm = TRUE),\n    share_among_excessive_delay_10 = n_distinct(trip_uid[excessive_delay_10]) / sum(trips$excessive_delay_10, na.rm = TRUE),\n    share_among_cancel_or_partial_completion = n_distinct(trip_uid[cancel_or_partial_completion]) / sum(trips$cancel_or_partial_completion, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  arrange(desc(pmax(share_among_excessive_delay_10, share_among_cancel_or_partial_completion, na.rm = TRUE)))\n\ncategory_rates <- trip_category %>%\n  group_by(category) %>%\n  summarise(\n    n_trips_with_category = n_distinct(trip_uid),\n    delayed_5_rate = mean(delayed_5, na.rm = TRUE),\n    excessive_delay_10_rate = mean(excessive_delay_10, na.rm = TRUE),\n    cancel_or_partial_completion_rate = mean(cancel_or_partial_completion, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  arrange(desc(pmax(excessive_delay_10_rate, cancel_or_partial_completion_rate, na.rm = TRUE)))\n\nsupport_threshold <- if_else(sum(category_rates$n_trips_with_category >= 50) >= 8, 50, 20)\n\npresence_display <- category_presence %>%\n  slice_head(n = 12) %>%\n  transmute(\n    Category = category,\n    `All trips` = fmt_pct(share_all_trips),\n    `Delay >5` = fmt_pct(share_among_delayed_5),\n    `Delay >10` = fmt_pct(share_among_excessive_delay_10),\n    `Cancel / partial` = fmt_pct(share_among_cancel_or_partial_completion)\n  )\n\nrates_display <- category_rates %>%\n  filter(n_trips_with_category >= support_threshold) %>%\n  slice_head(n = 12) %>%\n  transmute(\n    Category = category,\n    Trips = n_trips_with_category,\n    `Delay >5 rate` = fmt_pct(delayed_5_rate),\n    `Delay >10 rate` = fmt_pct(excessive_delay_10_rate),\n    `Cancel / partial rate` = fmt_pct(cancel_or_partial_completion_rate)\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclean_kable(presence_display, caption = \"Category presence among outcome groups\", align = \"lrrrr\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Category presence among outcome groups\n\n|Category            | All trips| Delay >5| Delay >10| Cancel / partial|\n|:-------------------|---------:|--------:|---------:|----------------:|\n|Passenger Delays    |     10.8%|    39.2%|     62.3%|            14.5%|\n|Marine Traffic      |     11.7%|    44.0%|     34.0%|            16.1%|\n|Max Out             |      1.5%|     5.2%|     10.2%|             0.8%|\n|Partially Completed |      0.8%|     0.0%|      0.0%|            10.2%|\n|Vessel Mechanical   |      0.8%|     3.5%|      7.7%|             2.0%|\n|Bypassed Landing    |      0.6%|     0.0%|      0.0%|             7.5%|\n|Landing Issue       |      2.2%|     5.5%|      6.7%|             6.1%|\n|Weather             |      0.4%|     0.7%|      1.7%|             4.1%|\n|Connectivity Issues |      2.5%|     2.4%|      2.6%|             3.7%|\n|Trip Cancelled      |      0.3%|     0.0%|      0.0%|             3.7%|\n|USCG Restriction    |      0.2%|     0.6%|      1.8%|             1.8%|\n|Hny                 |      0.3%|     1.0%|      1.6%|             0.4%|\n\n\n:::\n\n```{.r .cell-code}\nclean_kable(rates_display, caption = paste0(\"Outcome rates when category appears (support threshold n >= \", support_threshold, \")\"), align = \"lrrrr\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Outcome rates when category appears (support threshold n >= 50)\n\n|Category            | Trips| Delay >5 rate| Delay >10 rate| Cancel / partial rate|\n|:-------------------|-----:|-------------:|--------------:|---------------------:|\n|Partially Completed |  1160|          0.0%|           0.0%|                100.0%|\n|Trip Cancelled      |   426|          0.0%|           0.0%|                100.0%|\n|Bypassed Landing    |   881|          0.3%|           0.0%|                 96.9%|\n|Weather             |   589|         11.9%|           8.0%|                 79.8%|\n|USCG Restriction    |   347|         19.3%|          13.8%|                 60.2%|\n|Emergency           |    80|         25.0%|          17.5%|                 38.8%|\n|Landing Issue       |  3066|         18.7%|           5.8%|                 22.6%|\n|Vessel Mechanical   |  1071|         33.8%|          19.4%|                 20.8%|\n|Max Out             |  2167|         24.9%|          12.7%|                  4.1%|\n|Connectivity Issues |  3573|          7.1%|           2.0%|                 11.9%|\n|Hny                 |   392|         25.3%|          11.0%|                 11.7%|\n|Marine Traffic      | 16381|         27.9%|           5.6%|                 11.2%|\n\n\n:::\n:::\n\n\nThe first table shows which note categories appear most often among delayed or cancelled/partially completed trips. The second table flips the question: when a category appears, how often is that trip associated with delay or cancellation?\n\nPassenger delays and marine traffic are the most visible delay-associated note categories, but they point to different mechanisms. Passenger delays become especially concentrated among delay >10 trips, while marine traffic is more prominent in the broader delay >5 group. Rare categories such as vessel mechanical issues, weather, and USCG restrictions appear less often overall but have high disruption rates when they occur, making them operationally important despite their low frequency.\n\n#### Delay Decomposition\n\nThis is a median-based expected-time decomposition. A stop-level delay is decomposed into inherited previous-trip delay, carried within-trip delay, upstream landside delay, upstream waterside delay, and upstream wait when available. Vessel chains are reconstructed by vessel and operational sequence; consecutive trips by the same vessel are linked when they are operationally continuous. This is accounting/decomposition, not causal inference.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndecomp <- read_csv(decomp_file, show_col_types = FALSE)\ncomponent_cols <- c(\"inherited_prev_trip_delay\", \"carried_within_trip_delay\", \"upstream_landside_delay\", \"upstream_waterside_delay\", \"upstream_wait\")\ndisplay_components <- c(\"inherited_prev_trip_delay\", \"carried_within_trip_delay\", \"upstream_landside_delay\", \"upstream_waterside_delay\")\ncomponent_labels <- c(\n  inherited_prev_trip_delay = \"Inherited previous-trip delay\",\n  carried_within_trip_delay = \"Carried within-trip delay\",\n  upstream_landside_delay   = \"Upstream landside delay\",\n  upstream_waterside_delay  = \"Upstream waterside delay\",\n  upstream_wait             = \"Upstream wait\"\n)\n\neligible <- decomp %>%\n  mutate(eligible_flag = eligible_arrival_decomp %in% c(TRUE, 1, \"TRUE\", \"true\", \"1\")) %>%\n  filter(eligible_flag)\n\ndecomp_long <- eligible %>%\n  mutate(`Delay >5` = arrival_delay_min > 5, `Delay >10` = arrival_delay_min > 10) %>%\n  select(trip_key, stop_id, stop_sequence, `Delay >5`, `Delay >10`, all_of(component_cols)) %>%\n  pivot_longer(all_of(component_cols), names_to = \"component\", values_to = \"component_minutes\") %>%\n  mutate(Component = dplyr::recode(component, !!!component_labels), displayed = component %in% display_components)\n\ndecomp_groups <- bind_rows(\n  decomp_long %>% filter(`Delay >5`)  %>% mutate(delay_group = \"Delay >5\"),\n  decomp_long %>% filter(`Delay >10`) %>% mutate(delay_group = \"Delay >10\")\n)\n\ncomponent_summary <- decomp_groups %>%\n  group_by(delay_group, component, Component, displayed) %>%\n  summarise(avg_min = mean(component_minutes, na.rm = TRUE),\n            positive_avg_min = pmax(avg_min, 0), .groups = \"drop\") %>%\n  group_by(delay_group) %>%\n  mutate(share = if_else(displayed, positive_avg_min / sum(positive_avg_min[displayed], na.rm = TRUE), NA_real_)) %>%\n  ungroup()\n\ncomponent_table_display <- component_summary %>%\n  select(delay_group, Component, avg_min, share) %>%\n  pivot_wider(names_from = delay_group, values_from = c(avg_min, share), names_glue = \"{delay_group}_{.value}\") %>%\n  mutate(Component = factor(Component, levels = c(\"Inherited previous-trip delay\", \"Carried within-trip delay\",\n                                                   \"Upstream landside delay\", \"Upstream waterside delay\", \"Upstream wait\"))) %>%\n  arrange(Component) %>%\n  mutate(Component = as.character(Component)) %>%\n  transmute(\n    Component,\n    `Delay >5 avg min`  = round(`Delay >5_avg_min`, 2),\n    `Delay >5 share`    = if_else(is.na(`Delay >5_share`),  \"—\", fmt_pct(`Delay >5_share`)),\n    `Delay >10 avg min` = round(`Delay >10_avg_min`, 2),\n    `Delay >10 share`   = if_else(is.na(`Delay >10_share`), \"—\", fmt_pct(`Delay >10_share`))\n  )\n\nplot_components <- component_summary %>%\n  filter(displayed) %>%\n  mutate(Component = factor(Component, levels = rev(c(\"Inherited previous-trip delay\", \"Carried within-trip delay\",\n                                                       \"Upstream landside delay\", \"Upstream waterside delay\"))))\n\ndecomp_bar <- ggplot(plot_components, aes(x = delay_group, y = positive_avg_min, fill = Component)) +\n  geom_col(width = 0.65) +\n  scale_fill_manual(values = muted_palette) +\n  labs(title = \"Average Delay Components\", x = NULL, y = \"Average component minutes\") +\n  plot_theme\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(decomp_bar)\n```\n\n::: {.cell-output-display}\n![Average component minutes among stop observations with delay greater than 5 or 10 minutes.](technical-report_files/figure-html/decomposition-output-1.png){width=672}\n:::\n\n```{.r .cell-code}\nclean_kable(component_table_display, caption = \"Average delay components and displayed-component shares\", align = \"lrrrr\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Average delay components and displayed-component shares\n\n|Component                     | Delay >5 avg min| Delay >5 share| Delay >10 avg min| Delay >10 share|\n|:-----------------------------|----------------:|--------------:|-----------------:|---------------:|\n|Inherited previous-trip delay |             6.33|          64.7%|             11.16|           68.4%|\n|Carried within-trip delay     |             2.20|          22.4%|              3.45|           21.1%|\n|Upstream landside delay       |             0.56|           5.7%|              0.96|            5.9%|\n|Upstream waterside delay      |             0.71|           7.2%|              0.74|            4.5%|\n|Upstream wait                 |             0.02|              —|              0.01|               —|\n\n\n\nAverage component minutes among stop observations with delay greater than 5 or 10 minutes.\n:::\n:::\n\n\nThe decomposition shows that most delayed stop observations are not mainly created at the current stop or segment. Inherited previous-trip delay is the largest component in both groups, accounting for 64.7% of displayed component minutes among delay >5 observations and 68.4% among delay >10 observations. Carried within-trip delay is the second-largest component, contributing about one-fifth of displayed delay in both groups. Newly generated upstream landside and waterside components are much smaller on average.\n\nThe severity difference is also important. Delay >10 observations have much larger inherited delay than delay >5 observations, while the shares of landside and waterside delay remain comparatively small. This suggests that severe delay is often the result of propagation through the vessel chain rather than a local event at the delayed stop.\n\n#### Delay Genesis\n\nThis section traces delayed stop observations backward through the same vessel chain. Targets use `arrival_delay_min > 5` and `arrival_delay_min > 10`. A major source is a single landside event greater than 5 minutes or a single waterside event greater than 5 minutes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstop_label      <- if (\"stop_name\" %in% names(decomp)) \"stop_name\" else \"stop_id\"\nprev_stop_label <- if (\"prev_stop_name\" %in% names(decomp)) \"prev_stop_name\" else \"prev_stop_id\"\nvessel_col      <- if (\"vessel_id\" %in% names(decomp)) \"vessel_id\" else if (\"vessel\" %in% names(decomp)) \"vessel\" else NA_character_\nif (is.na(vessel_col)) stop(\"A vessel identifier is required for delay genesis tracing.\")\n\ntimeline0 <- decomp %>%\n  mutate(\n    scheduled_ts  = suppressWarnings(as.POSIXct(scheduled_time_original, tz = \"America/New_York\")),\n    eligible_flag = eligible_arrival_decomp %in% c(TRUE, 1, \"TRUE\", \"true\", \"1\")\n  )\n\ntrip_bounds <- timeline0 %>%\n  group_by(.data[[vessel_col]], trip_key) %>%\n  summarise(trip_start_ts = min(scheduled_ts, na.rm = TRUE),\n            trip_end_ts   = max(scheduled_ts, na.rm = TRUE), .groups = \"drop\") %>%\n  arrange(.data[[vessel_col]], trip_start_ts, trip_end_ts, trip_key) %>%\n  group_by(.data[[vessel_col]]) %>%\n  mutate(\n    prev_trip_end_ts = lag(trip_end_ts),\n    trip_gap_min     = as.numeric(difftime(trip_start_ts, prev_trip_end_ts, units = \"mins\")),\n    chain_break      = is.na(trip_gap_min) | trip_gap_min > 30,\n    vessel_chain_id  = paste(.data[[vessel_col]], cumsum(chain_break), sep = \"_\")\n  ) %>%\n  ungroup() %>%\n  select(.data[[vessel_col]], trip_key, vessel_chain_id, trip_start_ts, trip_gap_min)\n\ntimeline <- timeline0 %>%\n  left_join(trip_bounds, by = c(vessel_col, \"trip_key\")) %>%\n  mutate(\n    positive_landside_delay  = pmax(replace_na(upstream_landside_delay,  0), 0),\n    positive_waterside_delay = pmax(replace_na(upstream_waterside_delay, 0), 0),\n    observed_landing  = coalesce(as.character(.data[[stop_label]]),      as.character(stop_id)),\n    source_from_landing = coalesce(as.character(.data[[prev_stop_label]]), as.character(prev_stop_id), \"Origin\"),\n    source_to_landing = observed_landing,\n    observed_segment  = paste(source_from_landing, \"->\", observed_landing),\n    source_segment    = paste(source_from_landing, \"->\", observed_landing),\n    row_top_generated_delay = pmax(positive_landside_delay, positive_waterside_delay),\n    row_top_source_type = case_when(\n      row_top_generated_delay <= 0 ~ NA_character_,\n      positive_landside_delay >= positive_waterside_delay ~ \"Landside\",\n      TRUE ~ \"Waterside\"\n    ),\n    major_landside  = positive_landside_delay  > 5,\n    major_waterside = positive_waterside_delay > 5\n  ) %>%\n  arrange(vessel_chain_id, scheduled_ts, trip_start_ts, trip_key, stop_sequence) %>%\n  group_by(vessel_chain_id) %>%\n  mutate(\n    row_order_within_chain       = row_number(),\n    cumulative_positive_generated = cumsum(positive_landside_delay + positive_waterside_delay),\n    cumulative_major_sources      = cumsum(major_landside) + cumsum(major_waterside)\n  ) %>%\n  ungroup()\n\ntop_source_by_chain <- function(chain_df) {\n  chain_df <- chain_df %>% arrange(row_order_within_chain)\n  best_delay <- numeric(nrow(chain_df)); best_type <- character(nrow(chain_df))\n  best_landing <- character(nrow(chain_df)); best_segment <- character(nrow(chain_df))\n  current_best <- 0; current_type <- NA_character_; current_landing <- NA_character_; current_segment <- NA_character_\n  for (i in seq_len(nrow(chain_df))) {\n    if (!is.na(chain_df$row_top_generated_delay[i]) && chain_df$row_top_generated_delay[i] > current_best) {\n      current_best    <- chain_df$row_top_generated_delay[i]\n      current_type    <- chain_df$row_top_source_type[i]\n      current_landing <- chain_df$source_from_landing[i]\n      current_segment <- chain_df$source_segment[i]\n    }\n    best_delay[i] <- current_best; best_type[i] <- current_type\n    best_landing[i] <- current_landing; best_segment[i] <- current_segment\n  }\n  chain_df %>% mutate(\n    top_source_generated_minutes = best_delay,\n    top_source_type    = na_if(best_type, \"\"),\n    top_source_landing = na_if(best_landing, \"\"),\n    top_source_segment = na_if(best_segment, \"\")\n  )\n}\n\ntimeline <- timeline %>% group_split(vessel_chain_id) %>% map_dfr(top_source_by_chain)\n\nobserved_landing_den  <- timeline %>% filter(eligible_flag) %>% count(observed_landing,    name = \"Observed total observations\")\nobserved_segment_den  <- timeline %>% filter(eligible_flag) %>% count(observed_segment,    name = \"Observed total observations\")\ngenerated_landing_den <- timeline %>% filter(eligible_flag) %>% count(source_from_landing, name = \"Generated total source observations\")\ngenerated_segment_den <- timeline %>% filter(eligible_flag) %>% count(source_segment,      name = \"Generated total source observations\")\n\ntarget_base <- timeline %>%\n  filter(eligible_flag, arrival_delay_min > 5) %>%\n  transmute(\n    target_id_base = row_number(),\n    observed_landing, observed_segment, arrival_delay_min,\n    cumulative_positive_generated,\n    num_major_sources        = cumulative_major_sources,\n    top_source_generated_minutes,\n    top_source_type, top_source_landing, top_source_segment,\n    top_source_share = if_else(cumulative_positive_generated > 0,\n                               top_source_generated_minutes / cumulative_positive_generated, NA_real_)\n  )\n\ngenesis_targets <- bind_rows(\n  target_base %>% mutate(delay_group = \"delay_gt5\",  delay_group_label = \"Delay >5\"),\n  target_base %>% filter(arrival_delay_min > 10) %>% mutate(delay_group = \"delay_gt10\", delay_group_label = \"Delay >10\")\n) %>%\n  mutate(\n    target_id    = paste(delay_group, target_id_base, sep = \"_\"),\n    genesis_type = case_when(\n      cumulative_positive_generated <= 0 | is.na(cumulative_positive_generated) ~ \"No traced positive source\",\n      num_major_sources == 1 & top_source_share >= 0.5 ~ \"Single major\",\n      num_major_sources >= 2 ~ \"Multiple major\",\n      TRUE ~ \"Cumulative\"\n    )\n  )\n\nclassified_targets <- genesis_targets %>% filter(genesis_type %in% c(\"Single major\", \"Multiple major\", \"Cumulative\"))\n\ngenesis_type_summary <- classified_targets %>%\n  count(delay_group, delay_group_label, genesis_type, name = \"n_targets\") %>%\n  group_by(delay_group) %>%\n  mutate(share_of_classified_targets = n_targets / sum(n_targets)) %>%\n  ungroup()\n\ngenesis_type_bar <- ggplot(genesis_type_summary, aes(x = delay_group_label, y = share_of_classified_targets, fill = genesis_type)) +\n  geom_col(width = 0.65) +\n  scale_y_continuous(labels = percent_format()) +\n  scale_fill_manual(values = c(\"Single major\" = accent, \"Multiple major\" = gold, \"Cumulative\" = blue)) +\n  labs(title = \"Delay Genesis Type\", x = NULL, y = \"Share of classified delayed observations\") +\n  plot_theme\n\ntop_source_event_summary <- classified_targets %>%\n  count(delay_group, delay_group_label, top_source_type, name = \"n_targets\") %>%\n  group_by(delay_group) %>%\n  mutate(share_of_targets = n_targets / sum(n_targets)) %>%\n  ungroup()\n\ntop_source_event_plot <- ggplot(top_source_event_summary, aes(x = delay_group_label, y = share_of_targets, fill = top_source_type)) +\n  geom_col(width = 0.65) +\n  scale_y_continuous(labels = percent_format()) +\n  scale_fill_manual(values = c(\"Landside\" = accent, \"Waterside\" = coral)) +\n  labs(title = \"Top Source Event Type\", x = NULL, y = \"Share of classified delayed observations\") +\n  plot_theme\n\nmake_location_tables <- function(geography = c(\"landing\", \"segment\")) {\n  geography   <- match.arg(geography)\n  obs_col     <- if (geography == \"landing\") \"observed_landing\" else \"observed_segment\"\n  gen_col     <- if (geography == \"landing\") \"top_source_landing\" else \"top_source_segment\"\n  obs_den     <- if (geography == \"landing\") observed_landing_den else observed_segment_den\n  gen_den     <- if (geography == \"landing\") generated_landing_den else generated_segment_den\n  obs_den_col <- if (geography == \"landing\") \"observed_landing\" else \"observed_segment\"\n  gen_den_col <- if (geography == \"landing\") \"source_from_landing\" else \"source_segment\"\n\n  observed <- genesis_targets %>%\n    filter(delay_group == \"delay_gt5\") %>%\n    count(Location = .data[[obs_col]], name = \"Observed delayed count\") %>%\n    left_join(rename(obs_den, Location = all_of(obs_den_col)), by = \"Location\") %>%\n    mutate(`Observed delay rate` = `Observed delayed count` / `Observed total observations`)\n\n  generated <- classified_targets %>%\n    filter(delay_group == \"delay_gt5\", !is.na(.data[[gen_col]])) %>%\n    count(Location = .data[[gen_col]], name = \"Generated linked delay count\") %>%\n    left_join(rename(gen_den, Location = all_of(gen_den_col)), by = \"Location\") %>%\n    mutate(`Generated source-linked rate` = `Generated linked delay count` / `Generated total source observations`)\n\n  obs_support <- if (sum(observed$`Observed total observations` >= 100, na.rm = TRUE) >= 5) 100 else 50\n  gen_support <- if (sum(generated$`Generated total source observations` >= 100, na.rm = TRUE) >= 5) 100 else 50\n\n  count_table <- full_join(\n    observed  %>% arrange(desc(`Observed delayed count`))       %>% mutate(Rank = row_number()) %>% slice_head(n = 5) %>% select(Rank, `Observed delay location` = Location, `Observed delayed count`),\n    generated %>% arrange(desc(`Generated linked delay count`)) %>% mutate(Rank = row_number()) %>% slice_head(n = 5) %>% select(Rank, `Generated source location` = Location, `Generated linked delay count`),\n    by = \"Rank\"\n  ) %>% arrange(Rank)\n\n  rate_table <- full_join(\n    observed  %>% filter(`Observed total observations`        >= obs_support) %>% arrange(desc(`Observed delay rate`),         desc(`Observed delayed count`))       %>% mutate(Rank = row_number()) %>% slice_head(n = 5) %>% select(Rank, `Observed delay location` = Location, `Observed delayed count`, `Observed total observations`, `Observed delay rate`),\n    generated %>% filter(`Generated total source observations` >= gen_support) %>% arrange(desc(`Generated source-linked rate`), desc(`Generated linked delay count`)) %>% mutate(Rank = row_number()) %>% slice_head(n = 5) %>% select(Rank, `Generated source location` = Location, `Generated linked delay count`, `Generated total source observations`, `Generated source-linked rate`),\n    by = \"Rank\"\n  ) %>% arrange(Rank)\n\n  list(count = count_table, rate = rate_table)\n}\n\nlanding_gt5 <- make_location_tables(\"landing\")\nsegment_gt5 <- make_location_tables(\"segment\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(genesis_type_bar)\n```\n\n::: {.cell-output-display}\n![Genesis types among classified delayed observations.](technical-report_files/figure-html/genesis-output-1.png){width=672}\n:::\n:::\n\n\nMost delayed observations are classified as cumulative rather than being explained by one large source event. This is especially true for the broader delay >5 group. For delay >10 observations, the share of single-major and multiple-major cases increases, indicating that severe delays are more likely to involve at least one large upstream landside or waterside increment.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(top_source_event_plot)\n```\n\n::: {.cell-output-display}\n![Top source event type for classified delayed observations.](technical-report_files/figure-html/genesis-event-output-1.png){width=672}\n:::\n:::\n\n\nFor delay >5 observations, top source events are roughly balanced, with waterside sources slightly more prominent. For delay >10 observations, the split shifts more toward landside sources, suggesting that the most severe traced delays may be more connected to landing, dwell, boarding, or turnaround-related processes at the upstream source location.\n\n**Observed versus generated locations.** The observed-location tables show where delays appear if we only look at delayed arrivals. The generated-source tables show where the top traced source events occur after applying the decomposition logic.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nformat_rate_table <- function(x) {\n  x %>% mutate(\n    `Observed delay rate`       = fmt_pct(`Observed delay rate`),\n    `Generated source-linked rate` = fmt_pct(`Generated source-linked rate`)\n  )\n}\n\nclean_kable(landing_gt5$count %>% rename(`Observed delay landing` = `Observed delay location`, `Generated source landing` = `Generated source location`), caption = \"Delay >5 landing comparison by count\", align = \"rlrlr\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Delay >5 landing comparison by count\n\n| Rank|Observed delay landing | Observed delayed count|Generated source landing | Generated linked delay count|\n|----:|:----------------------|----------------------:|:------------------------|----------------------------:|\n|    1|Wall St/Pier 11        |                   5565|Wall St/Pier 11          |                         9898|\n|    2|East 34th Street       |                   5068|East 34th Street         |                         3448|\n|    3|Dumbo/Fulton Ferry     |                   3330|Dumbo/Fulton Ferry       |                         2851|\n|    4|Sunset Park/BAT        |                   2774|East 90th St             |                         2588|\n|    5|Greenpoint             |                   2390|Hunters Point South      |                         2038|\n\n\n:::\n\n```{.r .cell-code}\nclean_kable(format_rate_table(landing_gt5$rate) %>% rename(`Observed delay landing` = `Observed delay location`, `Generated source landing` = `Generated source location`), caption = \"Delay >5 landing comparison by local rate\", align = \"rlrrlrrr\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Delay >5 landing comparison by local rate\n\n| Rank|Observed delay landing | Observed delayed count| Observed total observations|Observed delay rate | Generated source landing| Generated linked delay count| Generated total source observations| Generated source-linked rate|\n|----:|:----------------------|----------------------:|---------------------------:|:-------------------|------------------------:|----------------------------:|-----------------------------------:|----------------------------:|\n|    1|Rockaway               |                    869|                        7693|11.3%               |                 Rockaway|                         2023|                                8173|                        24.8%|\n|    2|Ferry Point Park       |                   1042|                        9265|11.2%               |            Corlears Hook|                         1688|                                8445|                        20.0%|\n|    3|Soundview              |                   1929|                       18883|10.2%               |          Wall St/Pier 11|                         9898|                               63024|                        15.7%|\n|    4|Corlears Hook          |                    853|                        8584|9.9%                |      Hunters Point South|                         2038|                               15911|                        12.8%|\n|    5|Sunset Park/BAT        |                   2774|                       29165|9.5%                |                Bay Ridge|                          860|                                8364|                        10.3%|\n\n\n:::\n\n```{.r .cell-code}\nclean_kable(segment_gt5$count %>% rename(`Observed delay segment` = `Observed delay location`, `Generated source segment` = `Generated source location`), caption = \"Delay >5 segment comparison by count\", align = \"rlrlr\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Delay >5 segment comparison by count\n\n| Rank|Observed delay segment                   | Observed delayed count|Generated source segment                | Generated linked delay count|\n|----:|:----------------------------------------|----------------------:|:---------------------------------------|----------------------------:|\n|    1|Wall St/Pier 11 -> Dumbo/Fulton Ferry    |                   1810|Wall St/Pier 11 -> Dumbo/Fulton Ferry   |                         4423|\n|    2|East 34th Street -> Greenpoint           |                   1577|Wall St/Pier 11 -> Stuyvesant Cove      |                         2694|\n|    3|Dumbo/Fulton Ferry -> Wall St/Pier 11    |                   1570|Hunters Point South -> East 34th Street |                         2038|\n|    4|Greenpoint -> North Williamsburg         |                   1426|Rockaway -> Sunset Park/BAT             |                         2020|\n|    5|North Williamsburg -> South Williamsburg |                   1306|Corlears Hook -> Dumbo/Fulton Ferry     |                         1688|\n\n\n:::\n\n```{.r .cell-code}\nclean_kable(format_rate_table(segment_gt5$rate) %>% rename(`Observed delay segment` = `Observed delay location`, `Generated source segment` = `Generated source location`), caption = \"Delay >5 segment comparison by local rate\", align = \"rlrrlrrr\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Delay >5 segment comparison by local rate\n\n| Rank|Observed delay segment                     | Observed delayed count| Observed total observations|Observed delay rate |              Generated source segment| Generated linked delay count| Generated total source observations| Generated source-linked rate|\n|----:|:------------------------------------------|----------------------:|---------------------------:|:-------------------|-------------------------------------:|----------------------------:|-----------------------------------:|----------------------------:|\n|    1|Sunset Park/BAT -> Wall St/Pier 11         |                   1066|                        8148|13.1%               |    Wall St/Pier 11 -> Stuyvesant Cove|                         2694|                                9474|                        28.4%|\n|    2|East 90th St -> Soundview                  |                   1170|                        9498|12.3%               |  Bay Ridge -> Gov. Island/Yankee Pier|                           73|                                 265|                        27.5%|\n|    3|Rockaway -> Sunset Park/BAT                |                    961|                        8133|11.8%               |           Rockaway -> Sunset Park/BAT|                         2020|                                8133|                        24.8%|\n|    4|Sunset Park/BAT -> Red Hook/Atlantic Basin |                    461|                        4009|11.5%               |   Corlears Hook -> Dumbo/Fulton Ferry|                         1688|                                8445|                        20.0%|\n|    5|Soundview -> Ferry Point Park              |                   1042|                        9265|11.2%               | Wall St/Pier 11 -> Dumbo/Fulton Ferry|                         4423|                               24237|                        18.2%|\n\n\n:::\n:::\n\n\nThe count-based location tables show that the places where delay is observed are not always the same as the places where delay is generated. Wall St/Pier 11 and East 34th Street are major observed delay locations by count, given their central role in the network. However, the generated-source rankings shift attention upstream to locations such as East 90th St and Hunters Point South. The rate-based tables identify locations that are delay-prone relative to their own activity volume — useful for diagnosing reliability risk at a specific landing or segment.\n\n#### Delay Recovery\n\nThis section focuses only on trip pairs where the next trip inherits more than 5 minutes of delay. Origin recovery means the next trip departs within 1 minute of the median-based expected departure time. Scheduled slack is recomputed as current trip scheduled origin time minus the previous trip terminal scheduled time for the same vessel.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nterminal_rows <- decomp %>%\n  group_by(trip_key) %>%\n  slice_max(order_by = stop_sequence, n = 1, with_ties = FALSE) %>%\n  ungroup() %>%\n  transmute(trip_key, terminal_scheduled_time_original = scheduled_time_original)\n\norigin_context <- decomp %>%\n  group_by(trip_key) %>%\n  slice_min(order_by = stop_sequence, n = 1, with_ties = FALSE) %>%\n  ungroup() %>%\n  transmute(\n    trip_key, trip_date = trip_date_et, route_id, direction, vessel_id,\n    schedule_daytype, schedule_season,\n    origin_scheduled_time_original = prev_stop_scheduled_time_original,\n    origin_departure_delay_total, inherited_prev_trip_delay\n  )\n\nrecovery_pairs_recomputed <- origin_context %>%\n  left_join(terminal_rows, by = \"trip_key\") %>%\n  arrange(vessel_id, origin_scheduled_time_original, terminal_scheduled_time_original, trip_key) %>%\n  group_by(vessel_id) %>%\n  mutate(\n    previous_terminal_scheduled_time_original = lag(terminal_scheduled_time_original),\n    planned_turnaround_gap_min = as.numeric(difftime(origin_scheduled_time_original,\n                                                      previous_terminal_scheduled_time_original, units = \"mins\"))\n  ) %>%\n  ungroup() %>%\n  mutate(\n    inherited_prev_trip_delay     = pmax(as.numeric(inherited_prev_trip_delay), 0, na.rm = FALSE),\n    origin_departure_delay_total  = as.numeric(origin_departure_delay_total),\n    origin_recovered_1min         = origin_departure_delay_total <= 1,\n    origin_recovered_minutes      = inherited_prev_trip_delay - origin_departure_delay_total\n  )\n\ninherit_levels <- c(\"5–10\", \"10–15\", \"15–20\", \"20–25\", \"25–30\", \"30+\")\nslack_levels   <- c(\"5–10\", \"10–15\", \"15–20\", \"20–25\", \"25–30\")\nmask_lookup <- tibble(\n  inherited_delay_bin = factor(inherit_levels, levels = inherit_levels),\n  inherited_floor     = c(5, 10, 15, 20, 25, 30)\n) %>%\n  crossing(tibble(slack_bin = factor(slack_levels, levels = slack_levels), slack_ceiling = c(10, 15, 20, 25, 30))) %>%\n  mutate(display_cell = inherited_floor < slack_ceiling)\n\nrecovery_base <- recovery_pairs_recomputed %>%\n  mutate(\n    inherited_delay = inherited_prev_trip_delay,\n    slack           = planned_turnaround_gap_min,\n    origin_recovered = origin_recovered_1min,\n    inherited_delay_bin = case_when(\n      inherited_delay <= 10 ~ \"5–10\",  inherited_delay <= 15 ~ \"10–15\",\n      inherited_delay <= 20 ~ \"15–20\", inherited_delay <= 25 ~ \"20–25\",\n      inherited_delay <= 30 ~ \"25–30\", TRUE ~ \"30+\"\n    ),\n    slack_bin = case_when(\n      slack <= 10 ~ \"5–10\",  slack <= 15 ~ \"10–15\",\n      slack <= 20 ~ \"15–20\", slack <= 25 ~ \"20–25\",\n      slack <= 30 ~ \"25–30\", TRUE ~ NA_character_\n    )\n  ) %>%\n  filter(inherited_delay > 5, !is.na(slack), slack >= 5, slack <= 30, !is.na(origin_recovered))\n\nrecovery_heatmap_data <- recovery_base %>%\n  mutate(inherited_delay_bin = factor(inherited_delay_bin, levels = inherit_levels),\n         slack_bin           = factor(slack_bin,           levels = slack_levels)) %>%\n  group_by(inherited_delay_bin, slack_bin) %>%\n  summarise(\n    n = n(),\n    origin_recovery_rate          = mean(origin_recovered,         na.rm = TRUE),\n    median_inherited_delay        = median(inherited_delay,        na.rm = TRUE),\n    median_slack                  = median(slack,                  na.rm = TRUE),\n    median_origin_departure_delay = median(origin_departure_delay_total, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  left_join(mask_lookup, by = c(\"inherited_delay_bin\", \"slack_bin\")) %>%\n  filter(display_cell)\n\nrecovery_heatmap <- ggplot(recovery_heatmap_data,\n                           aes(x = slack_bin, y = inherited_delay_bin, fill = origin_recovery_rate)) +\n  geom_tile(color = \"white\", linewidth = 0.7) +\n  geom_text(aes(label = paste0(percent(origin_recovery_rate, accuracy = 1), \"\\n\", \"n=\", n)), size = 3.3) +\n  scale_fill_gradient(low = \"#F6DCA8\", high = accent, labels = percent_format(), limits = c(0, 1)) +\n  labs(title = \"Origin Recovery by Inherited Delay and Slack\",\n       x = \"Scheduled slack (minutes)\", y = \"Inherited delay (minutes)\", fill = \"Recovered\") +\n  plot_theme\n\nscatter_data <- recovery_pairs_recomputed %>%\n  mutate(inherited_delay  = inherited_prev_trip_delay,\n         slack            = planned_turnaround_gap_min,\n         origin_recovered = origin_recovered_1min) %>%\n  filter(inherited_delay > 5, !is.na(slack), slack >= 5, slack <= 30,\n         inherited_delay <= 40, !is.na(origin_recovered))\n\nrecovery_scatter <- ggplot(scatter_data, aes(x = inherited_delay, y = slack, color = origin_recovered)) +\n  geom_point(alpha = 0.3, size = 1.2) +\n  coord_cartesian(ylim = c(5, 30), xlim = c(5, 40)) +\n  scale_color_manual(values = c(`TRUE` = accent, `FALSE` = coral),\n                     labels = c(`TRUE` = \"Recovered\", `FALSE` = \"Not recovered\")) +\n  labs(title = \"Origin Recovery Scatter\",\n       x = \"Inherited delay (minutes)\", y = \"Scheduled slack (minutes)\", color = NULL) +\n  plot_theme\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(recovery_heatmap)\n```\n\n::: {.cell-output-display}\n![Origin recovery among trips inheriting more than 5 minutes of delay.](technical-report_files/figure-html/recovery-output-1.png){width=672}\n:::\n\n```{.r .cell-code}\nprint(recovery_scatter)\n```\n\n::: {.cell-output-display}\n![Origin recovery among trips inheriting more than 5 minutes of delay.](technical-report_files/figure-html/recovery-output-2.png){width=672}\n:::\n:::\n\n\nThe recovery heatmap shows a clear interaction between inherited delay and scheduled slack. When inherited delay is only 5–10 minutes, recovery becomes much more likely as slack increases: recovery is 13% with 5–10 minutes of slack, 31% with 10–15 minutes, and reaches 70–83% once slack is above 15 minutes. The scatter plot confirms the heatmap pattern: recovered trips cluster where inherited delay is small and scheduled slack is large.\n\n#### Conclusion\n\nTogether, these EDA modules show that ferry delay is operationally structured. Trip notes identify recurring disruption categories. The decomposition shows that delayed stop observations are dominated by inherited and carried delay rather than only newly generated local delay. Genesis tracing further shows that the place where delay is observed is not always the place where delay is generated; upstream landings and segments can create delay that is recorded later downstream. Finally, the recovery analysis shows that scheduled slack can absorb moderate inherited delay, but recovery becomes unlikely when inherited delay is large or when slack is only marginal.\n\n## Automatic Identification System (AIS) Data\n**By: Sujan Kakumanu**\n\n### Background\nAt a high level, AIS (Automatic Identification System) allows large marine vehicles to report their status (location, speed, heading, voyage data, etc). This is used to communicate with other vessels and authorities on-shore (traffic management, for example).\n\nDepending on the size of the vessel, data can be transmitted as frequently as every 2 seconds. As a result, the provided data sets are incredibly large. The analysis code below focuses on one CSV (AIS from June 2025 in NY Harbor). This file is still too large, and will not be uploaded alongside this script.\n\n**Sources:**\n\nAIS Data Dictionary: https://coast.noaa.gov/data/marinecadastre/ais/data-dictionary.pdf \nVessel type codes: https://coast.noaa.gov/data/marinecadastre/ais/VesselTypeCodes2018.pdf \nUS Coast Guard AIS Description: https://www.navcen.uscg.gov/automatic-identification-system-overview\n\n**Columns of Interest (grouped by loose categories):**\n\n- Vessel features:\n  - mmsi: a unique identifying integer\n  - vessel_name: name of the ship, seems to include the operator name\n  - vessel_type: A code that defines vessel type, cargo type, etc. See link above.\n  - length; width: in meters\n- Travel features:\n  - sog: speed in knots\n  - cog: course in degrees (course is the actual direction of the vessel, taking into account wind and current)\n  - base_date_time: UTC date time\n  - heading: true heading in degrees (the direction of the bow w.r.t true north)\n  - latitude; longitude: in decimal degree\n  \n### Distributions of Select Variables\n\nFor this initial exploration, I want to trim the data down to a specific time frame to help with analysis speed. I picked a Wednesday in June to hopefully get a typical working day of data in the harbor.\n\n::: {.cell}\n\n```{.r .cell-code}\n# Loading the data. Trimming it to Wednesday June 4th for easier analysis at this point.\nais_06_2025 <- read.csv(\"AIS_2025.06.csv\")\n\nais_06_16_2025_trimmed <- ais_06_2025 %>%\n  mutate(base_date_time = ymd_hms(base_date_time)) %>%\n  filter(date(base_date_time) == ymd(\"2025-06-16\"))\n\nwrite.csv(ais_06_16_2025_trimmed, \"AIS_2025_06_16_filtered.csv\", row.names = FALSE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nais_06_16_2025_trimmed <- read.csv(\"../exploratory_code/ais-eda/AIS_2025_06_16_filtered.csv\")\n```\n:::\n\n\n**Frequency of Vessel Types**\nBelow is a visual of how many pings certain vessel types are sending.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ais_06_16_2025_trimmed, aes(x = as.factor(vessel_type))) +\n  geom_bar(fill = \"steelblue\") +\n  labs(title = \"Frequency of Vessel Types\",\n       subtitle = \"June 16, 2025 - NY Harbor\",\n       x = \"Vessel Type Code\",\n       y = \"Number of Pings\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\nMost Common Vessel codes: \n\n- 31: Tug and Tow - Towing\n- 37: Pleasure craft\n- 52: Tug and Tow - Tugging\n- 60: All ships of passenger type\n\n**Vessel Size**\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(ais_06_16_2025_trimmed, aes(x = length)) +\n  geom_histogram(binwidth = 10, fill = \"steelblue\", color = \"white\") +\n  labs(title = \"Distribution of Vessel Lengths\",\n       x = \"Length (meters)\",\n       y = \"Count\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n**Traffic Volume**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Note that I ignore docking/docked ships. Noticed a lot of zeros\nais_06_16_2025_trimmed %>%\n  filter(sog > 0.5) %>% \n  ggplot(aes(x = sog)) +\n  geom_histogram(binwidth = 1, fill = \"darkblue\", color = \"white\") +\n  labs(title = \"Speed Distribution of Moving Vessels\",\n       subtitle = \"Excludes stationary vessels (SOG > 0.5 knots)\",\n       x = \"Speed Over Ground (knots)\",\n       y = \"Number of Pings\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n### Hexbin Visualizations\nWe can aggregate traffic to hexbin cells to understand traffic patterns.\nInstead of counting **pings** (raw transmissions) per hexbin, we count **unique vessels** \n(distinct MMSIs). This matters because a slow-moving tanker anchored for hours generates \nfar more pings than a fast tug crossing the harbor — ping count reflects dwell time, not \ntraffic volume. Vessel count is a more honest measure of how busy a given area of the \nharbor actually is.\n\n**Data Loading**\nSame June 16–22 subset as before.\n\n::: {.cell}\n\n```{.r .cell-code}\nais <- read.csv(\"../exploratory_code/ais-eda/AIS_2025_06_16_filtered.csv\") %>%\n  mutate(\n    base_date_time = ymd_hms(base_date_time),\n    date = as.Date(base_date_time),\n    hour = hour(base_date_time)\n  )\n```\n:::\n\nWe created a geojson containing a stable hexbin grid to be used for our project.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nais_sf <- ais %>%\n  filter(sog > 0.5) %>%\n  drop_na(longitude, latitude) %>%\n  st_as_sf(coords = c(\"longitude\", \"latitude\"), crs = 4326) %>%\n  st_transform(32118)\n\nfishnet <- st_read(\"../exploratory_code/hex_grid_100m.geojson\") %>%\n  st_transform(32118) %>%\n  mutate(grid_id = row_number())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `hex_grid_100m' from data source \n  `/Users/sujankakumanu/Documents/musa-8010-nycedc/exploratory_code/hex_grid_100m.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 70742 features and 0 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 293123.6 ymin: 43240.14 xmax: 314873.6 ymax: 71501.44\nProjected CRS: NAD83 / New York Long Island\n```\n\n\n:::\n:::\n\n\n**Aggregating to Vessel Count**\n\nWe filter to moving vessels (SOG > 0.5 knots) to exclude anchored or docked ships.\nCount **distinct MMSIs** per cell per hour — not raw pings.\n\n::: {.cell}\n\n```{.r .cell-code}\ntraffic <- fishnet %>%\n  st_join(ais_sf) %>%\n  filter(!is.na(mmsi)) %>%\n  group_by(grid_id, date, hour) %>%\n  summarise(\n    vessel_count = n_distinct(mmsi),\n    ping_count = n(),\n    .groups = \"drop\"\n  )\n```\n:::\n\n\n**Ping Count vs. Vessel Count**\nThis is a quick sanity check to make sure we're on the right path.\nMost hexbin cells have more pings than unique vessels, which is exactly what we expect. \nVessels passing through a cell generate multiple pings.\n\n::: {.cell}\n\n```{.r .cell-code}\ntraffic %>%\n  st_drop_geometry() %>%\n  group_by(grid_id) %>%\n  summarise(\n    total_pings = sum(ping_count),\n    total_vessels = sum(vessel_count),\n    .groups = \"drop\"\n  ) %>%\n  filter(total_pings > 0) %>%\n  ggplot(aes(x = total_pings, y = total_vessels)) +\n  geom_point(alpha = 0.3, color = \"steelblue\") +\n  geom_abline(linetype = \"dashed\", color = \"red\") +\n  labs(\n    title = \"Ping Count vs. Vessel Count per Hexbin Cell\",\n    x = \"Total Pings\",\n    y = \"Total Unique Vessels\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/ping-vs-vessel-1.png){width=672}\n:::\n:::\n\n\n#### Harbor-Wide Vessel Density\nAggregated across the full day to show overall traffic patterns in the harbor.\nNote the use of a log scale — vessel counts vary dramatically across cells, and\na log transformation allows us to see variation in both busy and quiet areas.\nLog10 is used for better interpretability.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntraffic_day <- traffic %>%\n  st_drop_geometry() %>%\n  group_by(grid_id) %>%\n  summarise(vessel_count = sum(vessel_count), .groups = \"drop\")\n\nfishnet %>%\n  left_join(traffic_day, by = \"grid_id\") %>%\n  ggplot() +\n  geom_sf(aes(fill = vessel_count), color = NA) +\n  scale_fill_viridis_c(option = \"inferno\", trans = \"log10\", na.value = \"grey90\") +\n  labs(\n    title = \"Harbor-Wide Vessel Density (Unique Vessels)\",\n    subtitle = \"NY Harbor — June 16, 2025\",\n    fill = \"Vessel Count (Log10)\"\n  ) +\n  theme_minimal() +\n  theme(axis.text = element_blank(), panel.grid = element_blank())\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/map-harbor-density-1.png){width=672}\n:::\n:::\n\nHere, we can see some clear patterns that are validated by our domain knowledge. The East River shows a lot of traffic in a tight corridor. Same with the Hudson River, flowing into the area north of the Staten Island.\n\n\n#### Sample Stop-Level Traffic Exploration\nJust to explore, I take 3 major ferry stops (hunters point south isn't \"major\", but just an interesting one):\nQuestion: **how does vessel traffic in the surrounding area vary across the day?**\nNOTE: Stops are hard coded here. This is only for exploration purposes.\nNOTE 2: We're using 500m buffers to understand patterns further away from stops. The fishnet is still 200m.\n\n::: {.cell}\n\n```{.r .cell-code}\nferry_stops <- tibble(\n  stop_name = c(\"Wall St / Pier 11\", \"East 34th St\", \"Hunters Point South\"),\n  longitude = c(-74.00625, -73.97095, -73.96137),\n  latitude  = c(40.70322,  40.74409,  40.74185)\n) %>%\n  st_as_sf(coords = c(\"longitude\", \"latitude\"), crs = 4326) %>%\n  st_transform(32118)\n\nstop_buffers <- ferry_stops %>%\n  mutate(geometry = st_buffer(geometry, dist = 500))\n\nstop_cells <- fishnet %>%\n  st_join(stop_buffers) %>%\n  filter(!is.na(stop_name)) %>%\n  st_drop_geometry() %>%\n  select(grid_id, stop_name)\n\nstop_traffic <- traffic %>%\n  st_drop_geometry() %>%\n  inner_join(stop_cells, by = \"grid_id\") %>%\n  group_by(stop_name, date, hour) %>%\n  summarise(vessel_count = sum(vessel_count), .groups = \"drop\") %>%\n  mutate(\n    date = as.Date(date),\n    datetime = ymd_h(paste(date, hour))\n  )\n\nggplot(stop_traffic, aes(x = datetime, y = vessel_count, color = stop_name)) +\n  geom_line() +\n  geom_point(size = 1.5) +\n  labs(\n    title = \"Vessel Traffic Near Ferry Stops\",\n    subtitle = \"500m buffer — June 16, 2025\",\n    x = NULL,\n    y = \"Unique Vessels per Hour\",\n    color = \"Stop\"\n  ) +\n  scale_color_viridis_d(option = \"turbo\") +\n  theme_minimal() +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/stop-traffic-timeseries-1.png){width=672}\n:::\n:::\n\n\n#### In-Water Traffic Along Route Corridors\n\nBeyond stop-level traffic, we want to look at traffic ferries encounter **as they transit between stops**. \nThis is particularly valuable for understanding in-water delays.\n\nThe route geometry below is a straight-line placeholder between East 34th St and\nHunters Point South. \nNOTE: **This will be replaced with real SWIFTLY route geometry once that data is wrangled.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Placeholder: straight line East 34th St -> Hunters Point South\n# To be replaced with SWIFTLY route geometry\nroute_placeholder <- st_sfc(\n  st_linestring(\n    matrix(c(-73.97095, 40.74409,\n             -73.96137, 40.74185),\n           ncol = 2, byrow = TRUE)\n  ),\n  crs = 4326\n) %>%\n  st_transform(32118) %>%\n  st_sf() %>%\n  mutate(route_id = \"east_34th_to_hunters_point\")\n\n# Buffer 250m along the route corridor\nroute_buffer <- route_placeholder %>%\n  st_buffer(dist = 250)\n\n# Find fishnet cells intersecting the corridor\nroute_cells <- fishnet %>%\n  st_join(route_buffer) %>%\n  filter(!is.na(route_id)) %>%\n  st_drop_geometry() %>%\n  select(grid_id, route_id)\n\n# Vessel count along corridor by hour\nroute_traffic <- traffic %>%\n  st_drop_geometry() %>%\n  inner_join(route_cells, by = \"grid_id\") %>%\n  group_by(route_id, date, hour) %>%\n  summarise(vessel_count = sum(vessel_count), .groups = \"drop\") %>%\n  mutate(datetime = ymd_h(paste(date, hour)))\n\nggplot(route_traffic, aes(x = datetime, y = vessel_count)) +\n  geom_line(color = \"steelblue\") +\n  geom_point(size = 1.5, color = \"steelblue\") +\n  labs(\n    title = \"Vessel Traffic Along Route Segment\",\n    subtitle = \"Segment: East 34th St to Hunters Point South — 250m buffer, June 16, 2025\",\n    x = NULL,\n    y = \"Unique Vessels per Hour\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/route-traffic-1.png){width=672}\n:::\n:::\n\n\n\n#### Sample Modeling Row\n\nTo make the feature concrete, the tables below show what joined observations will\nlook like in the final modeling dataset. The first table shows the stop-level feature,\nthe second shows the route corridor feature. In practice these will be joined to the\nstop-level delay data by stop, route, date, and hour.\n\n::: {.cell}\n\n```{.r .cell-code}\nstop_traffic %>%\n  filter(hour %in% c(8, 12, 17)) %>%\n  select(stop_name, date, hour, vessel_count) %>%\n  arrange(stop_name, hour) %>%\n  knitr::kable(caption = \"Sample: AIS Traffic Feature at Stop Level\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Sample: AIS Traffic Feature at Stop Level\n\n|stop_name           |date       | hour| vessel_count|\n|:-------------------|:----------|----:|------------:|\n|East 34th St        |2025-06-16 |    8|            8|\n|East 34th St        |2025-06-16 |   12|           70|\n|East 34th St        |2025-06-16 |   17|           48|\n|Hunters Point South |2025-06-16 |    8|            7|\n|Hunters Point South |2025-06-16 |   12|           27|\n|Hunters Point South |2025-06-16 |   17|           15|\n|Wall St / Pier 11   |2025-06-16 |    8|            1|\n|Wall St / Pier 11   |2025-06-16 |   12|          104|\n|Wall St / Pier 11   |2025-06-16 |   17|           63|\n\n\n:::\n\n```{.r .cell-code}\nroute_traffic %>%\n  filter(hour %in% c(8, 12, 17)) %>%\n  select(route_id, date, hour, vessel_count) %>%\n  arrange(hour) %>%\n  knitr::kable(caption = \"Sample: AIS Traffic Feature Along Route Corridor\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Sample: AIS Traffic Feature Along Route Corridor\n\n|route_id                   |date       | hour| vessel_count|\n|:--------------------------|:----------|----:|------------:|\n|east_34th_to_hunters_point |2025-06-16 |    8|            8|\n|east_34th_to_hunters_point |2025-06-16 |   12|           73|\n|east_34th_to_hunters_point |2025-06-16 |   17|           46|\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 500m context buffer\ncrop_extent <- route_placeholder %>%\n  st_buffer(500) %>%\n  st_bbox()\n\ncorridor_traffic <- traffic %>%\n  st_drop_geometry() %>%\n  inner_join(route_cells, by = \"grid_id\") %>%\n  filter(hour %in% c(8, 12, 17)) %>%\n  group_by(grid_id, hour) %>%\n  summarise(vessel_count = sum(vessel_count), .groups = \"drop\") %>%\n  left_join(fishnet, by = \"grid_id\") %>%\n  st_as_sf()\n\nggplot() +\n  geom_sf(data = fishnet %>% st_crop(crop_extent), fill = \"grey95\", color = NA) +\n  geom_sf(data = corridor_traffic, aes(fill = vessel_count), color = NA) +\n  geom_sf(data = route_placeholder, color = \"white\", linewidth = 0.8) +\n  scale_fill_viridis_c(option = \"inferno\", na.value = \"grey80\") +\n  coord_sf(xlim = c(crop_extent[\"xmin\"], crop_extent[\"xmax\"]),\n           ylim = c(crop_extent[\"ymin\"], crop_extent[\"ymax\"])) +\n  facet_wrap(~hour, nrow = 1, labeller = as_labeller(c(\n    \"8\"  = \"08:00 AM\",\n    \"12\" = \"12:00 PM\",\n    \"17\" = \"05:00 PM\"\n  ))) +\n  labs(\n    title = \"Vessel Traffic Along Route Corridor by Hour\",\n    subtitle = \"East 34th St to Hunters Point South — 250m buffer, June 16, 2025\",\n    fill = \"Vessel Count\"\n  ) +\n  theme_minimal() +\n  theme(axis.text = element_blank(), panel.grid = element_blank())\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/route-corridor-maps-1.png){width=672}\n:::\n:::\n\n\n## Swiftly\n**By: Tyler Maynard**\n\n### Background\n\nThe Swiftly GPS dataset contains location data every 10-60 seconds from the NYC Ferry AVL system. Columns include vessel, route, trip, block, and coordinates. This will be especially useful in calculating the speed of the vehicle at various points in time, helping identify locations, routes, and trips where the system struggles with on-time performance.\n\n**Reference Week: June 16-22, 2025**\n\nFor the sake of processing power, we selected a \"sample week\" to conduct EDA for Swiftly GPS and AIS data. Based on conversations with NYCEDC, ridership is much higher in the summer months, especially on weekends. Thus, we chose a week during the summer, also including a holiday to evaluate any unique characteristics (if any) during special service days.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspecial_service <- data.frame(\n  dates = as.Date(c(\"2025-06-19\")))\n```\n:::\n\n\n### Data Import\n\nThe Swiftly GPS data set is available by month in CSV files. The following chunk reads the June 2025 CSV file, filters to the dates included in the sample week, and parses out each record's date and time into separate columns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Original csv\njun2025_original <- read.csv(\"../exploratory_code/swiftly_eda/swiftly_gps.2025_06.csv\")\n\n# Removing extra 'data.' from column names, removing unneeded columns\njun2025 <- jun2025_original %>%\n  rename_with(~ gsub(\"data.\", \"\", .x)) %>%\n  select(-(1:3), -(7))\n\n# Converting to datetime\njun2025$time <- ymd_hms(jun2025$time)\njun2025$timeProcessed <- ymd_hms(jun2025$timeProcessed)\n\n# Seeing how many unique values each column has\njun2025 %>%\n  summarise(across(everything(), n_distinct)) %>%\n  pivot_longer(cols = everything()) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|name                                    |   value|\n|:---------------------------------------|-------:|\n|time                                    | 1510826|\n|lat                                     |   63986|\n|lon                                     |   31883|\n|ispredictable                           |       2|\n|isLayover                               |       2|\n|isWaitStop                              |       2|\n|timeProcessed                           | 2740360|\n|vehicleId                               |      33|\n|headsign                                |      16|\n|blockassignmentorigin                   |       3|\n|assignmentId                            |    2166|\n|assignmentTime                          |    2834|\n|blockAssignmentMethod                   |       8|\n|blockId                                 |      28|\n|directionId                             |       3|\n|headwayMsec                             | 1779585|\n|previousVehicleId                       |      34|\n|previousVehicleSchedAdhMsec             |  611794|\n|routeId                                 |       8|\n|routeShortName                          |       8|\n|schedAdh                                |    3212|\n|schedAdhMsec                            |  758901|\n|scheduledHeadwayMsec                    |     193|\n|serviceId                               |       7|\n|serviceName                             |       7|\n|tripId                                  |    2169|\n|tripShortName                           |     395|\n|unpredictablestatus.type                |       2|\n|unpredictablestatus.details.blockId     |      27|\n|unpredictablestatus.details.serviceDate |      31|\n\n\n:::\n\n```{.r .cell-code}\n# Parse dates and times\njun2025 <- jun2025 %>%\n  mutate(\n    date_time = ymd_hms(time, tz = \"America/New_York\"),\n    processed_date_time = ymd_hms(timeProcessed, tz = \"America/New_York\"),\n\n    date = as.Date(date_time),\n    time = format(date_time, \"%H:%M:%S\"),\n    hour = substr(time,1,2),\n\n    dateProcessed = as.Date(processed_date_time),\n    timeProcessed = format(processed_date_time, \"%H:%M:%S\"),\n\n    dayOfWeek = if_else(wday(date, week_start = 1) %in% c(6,7), \"Weekend\", \"Weekday\"),\n    dayOfWeek = case_when(\n      date %in% special_service$dates ~ \"Holiday\",\n      TRUE ~ dayOfWeek)) %>%\n  select(date, time, dateProcessed, timeProcessed, dayOfWeek, headsign, tripShortName, everything(), date_time, processed_date_time)\n\njun2025_reference_week <- jun2025 %>%\n  filter(date %in% c(\"2025-06-16\",\"2025-06-17\",\"2025-06-18\",\"2025-06-19\",\"2025-06-20\",\"2025-06-21\",\"2025-06-22\")) %>%\n  filter(!is.na(tripId)) %>%\n  arrange(vehicleId, date_time)\nstr(jun2025_reference_week$time)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n chr [1:851238] \"06:21:24\" \"06:21:29\" \"06:21:44\" \"06:21:59\" \"06:22:14\" ...\n```\n\n\n:::\n:::\n\n\n### Shapefiles\n\nAs a way to add more spatial context to this analysis, the landings, routes, hydrology, and boroughs were extracted from the NYC Ferry and NYC OpenData websites. The hydrology object was trimmed to only include hydrology contained within the bounding box created around the study area.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlandings <- read_sf(\"../exploratory_code/swiftly_eda/Shapefiles/Landings/landings.shp\") %>%\n  st_transform(32118)\n\nlandings_east_river <- landings %>%\n  filter(!stop_id %in% c(\"37\",\"39\",\"43\",\"45\",\"46\",\"48\",\"49\",\"50\",\n    \"51\",\"52\",\"55\",\"56\",\"57\",\"58\",\"61\",\"62\",\n    \"16\",\"88\",\"103\",\"104\",\"105\",\"142\",\n    \"145\",\"149\",\"150\",\"151\")) %>%\n  st_transform(32118)\n\nroutes <- read_sf(\"../exploratory_code/swiftly_eda/Shapefiles/Routes/routes.shp\") %>%\n  group_by(route_id) %>%\n  summarise() %>%\n  st_transform(32118)\n\nboroughs <- read_sf(\"../exploratory_code/swiftly_eda/Shapefiles/Boroughs/boroughs.shp\") %>%\n  st_transform(32118)\n\nbbox_east_river <- st_bbox(landings_east_river)\nbbox_expanded_east_river <- bbox_east_river\nbbox_expanded_east_river[\"xmin\"] <- bbox_east_river[\"xmin\"] - 15000\nbbox_expanded_east_river[\"ymin\"] <- bbox_east_river[\"ymin\"] - 15000\nbbox_expanded_east_river[\"xmax\"] <- bbox_east_river[\"xmax\"] + 15000\nbbox_expanded_east_river[\"ymax\"] <- bbox_east_river[\"ymax\"] + 15000\nbbox_poly_east_river <- st_as_sfc(bbox_expanded_east_river)\n\nwater <- read_sf(\"../exploratory_code/swiftly_eda/Shapefiles/Hydrology/WBDHU2.shp\") %>%\n  st_transform(32118) %>%\n  summarise(geometry = st_union(geometry)) %>%\n  st_intersection(st_transform(st_as_sfc(st_bbox(bbox_expanded_east_river)), 32118))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbbox <- st_bbox(c(\n  xmin = -74.30603027343751,\n  ymin = 40.492915026895815,\n  xmax = -73.64959716796876,\n  ymax = 40.919739051062216\n), crs = 4326)\n\nbbox_area <- st_as_sfc(bbox) %>%\n  st_transform(32118)\n\nbbox_service_area <- boroughs %>%\n  st_transform(32118) %>%\n  st_bbox()\n```\n:::\n\n\n### Data Cleaning\n\nThe following chunk creates sf objects for each data point and computes new fields for feature engineering. Features created include:\n\n- **Knots**: based on the time and distance of the previous node of the same trip.\n- **Key identifiers**: for different analyses, generally including date, trip, and route.\n- **OTP**: classifies on-time performance at each node based on the schedule adherence column (`schedAdhMsec`).\n- **Excessively Late**: a binary field indicating whether a record is more than 10 minutes past the expected time.\n- **First Record Late**: indicates if the trip starts five minutes past its scheduled time.\n- **OTP Transition**: identifies trips where the OTP changes from one status to another (e.g., on-time to late).\n\nOf the 851,238 data points within this sample week, 25,558 were identified as excessively late — approximately three percent of all records.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npts <- st_as_sf(jun2025_reference_week, coords = c(\"lon\", \"lat\"), crs = 4326, remove = FALSE) %>%\n  st_transform(32118)\n\nxy <- st_coordinates(pts)\n\nstopifnot(nrow(jun2025_reference_week) == nrow(xy))\n\njun2025_reference_week <- jun2025_reference_week %>%\n  mutate(x = xy[, 1], y = xy[, 2]) %>%\n  group_by(date, blockId, routeId, tripId, directionId, dayOfWeek) %>%\n  arrange(date_time, .by_group = TRUE) %>%\n  mutate(\n    directionId = case_when(\n      directionId == 1 ~ \"NB\",\n      TRUE ~ \"SB\"\n    ),\n    isFirst = row_number() == 1,\n    isSecond = row_number() == 2,\n    dist_to_prev_m = round(sqrt((x - lag(x))^2 + (y - lag(y))^2), 2),\n    time_diff_sec  = as.numeric(difftime(date_time, lag(date_time), units = \"secs\")),\n    m_per_sec      = if_else(is.na(time_diff_sec) | time_diff_sec <= 0,\n                             0,\n                             round(dist_to_prev_m / time_diff_sec, 2)),\n    knots = m_per_sec * 1.94384,\n    date_route_trip_direction_vehicle_dow = paste(date, routeId, tripId, directionId, vehicleId, dayOfWeek, sep = \" \"),\n    key_identifier = paste(date, blockId, routeId, tripId, directionId, dayOfWeek, sep = \" \"),\n    dailyTrip = paste(dayOfWeek, routeId, tripId, sep = \" \"),\n    countDailyTrip = n(),\n    OTP = case_when(\n      schedAdhMsec < -60000 ~ \"Early\",\n      schedAdhMsec > 600000 ~ \"Excessively Late\",\n      schedAdhMsec > 300000 ~ \"Late\",\n      TRUE ~ \"Ontime\"\n    ),\n    excessivelyLate = case_when(\n      OTP == \"Excessively Late\" ~ 1,\n      TRUE ~ 0\n    ),\n    timeOfDay = as.integer(hour(date_time)),\n    firstRecordLate = if_else(isSecond == 1 & (OTP == \"Late\" | OTP == \"Excessively Late\"), \"Yes\", \"No\"),\n    OTP_prev = lag(OTP),\n    OTP_changed = coalesce(OTP != OTP_prev, FALSE),\n    OTP_transition = case_when(\n      isFirst ~ \"Start\",\n      is.na(OTP_prev) ~ \"Start\",\n      OTP == OTP_prev ~ \"No Change\",\n      TRUE ~ paste0(OTP_prev, \" -> \", OTP)\n    )\n  ) %>%\n  ungroup() %>%\n  select(-x, -y, -m_per_sec) %>%\n  select(dailyTrip, key_identifier, date_route_trip_direction_vehicle_dow, date, time, dateProcessed, timeProcessed, OTP, OTP_transition, excessivelyLate, timeOfDay, schedAdh, dayOfWeek,\n         dist_to_prev_m, time_diff_sec, knots, headsign, tripShortName,\n         everything(), date_time, processed_date_time)\n\nsummary_table <- data.frame(\n  Statistic = names(summary(jun2025_reference_week$knots)),\n  Value     = as.numeric(summary(jun2025_reference_week$knots)),\n  row.names = NULL\n)\n\njun2025_reference_week_sf <- st_as_sf(jun2025_reference_week, coords = c(\"lon\", \"lat\"), crs = 4326, remove = FALSE) %>%\n  st_transform(32118)\n\nkable(summary_table, digits = 2, caption = \"Summary of Knots\") %>%\n  kable_styling(\n    bootstrap_options = c(\"striped\", \"hover\"),\n    full_width = FALSE\n  ) %>%\n  column_spec(1:2, width = \"150px\")\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Summary of Knots</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Statistic </th>\n   <th style=\"text-align:right;\"> Value </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;width: 150px; \"> Min. </td>\n   <td style=\"text-align:right;width: 150px; \"> 0.00 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;width: 150px; \"> 1st Qu. </td>\n   <td style=\"text-align:right;width: 150px; \"> 3.11 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;width: 150px; \"> Median </td>\n   <td style=\"text-align:right;width: 150px; \"> 10.77 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;width: 150px; \"> Mean </td>\n   <td style=\"text-align:right;width: 150px; \"> 11.92 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;width: 150px; \"> 3rd Qu. </td>\n   <td style=\"text-align:right;width: 150px; \"> 20.57 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;width: 150px; \"> Max. </td>\n   <td style=\"text-align:right;width: 150px; \"> 4308.46 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n\n```{.r .cell-code}\njun2025_reference_week %>%\n  count(excessivelyLate, sort = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  excessivelyLate      n\n            <dbl>  <int>\n1               0 825681\n2               1  25557\n```\n\n\n:::\n\n```{.r .cell-code}\njun2025_reference_week_excessively_lates <- jun2025_reference_week %>%\n  filter(OTP == \"Excessively Late\")\n\njun2025_reference_week_excessively_lates_sf <- st_as_sf(jun2025_reference_week_excessively_lates, coords = c(\"lon\", \"lat\"), crs = 4326, remove = FALSE) %>%\n  st_transform(32118)\n\nhull <- concaveman(jun2025_reference_week_excessively_lates_sf)\nbbox_hull <- st_bbox(hull)\n\nggplot() +\n  geom_sf(data = boroughs, color = \"white\") +\n  geom_sf(data = hull, color = \"red\", fill = NA, size = 3) +\n  coord_sf(\n    xlim = c(bbox_east_river[\"xmin\"] - 10000, bbox_east_river[\"xmax\"] + 10000),\n    ylim = c(bbox_east_river[\"ymin\"] - 10000, bbox_east_river[\"ymax\"] + 10000),\n    expand = FALSE\n  ) +\n  labs(title = \"Excessively Late 'Zone' - Concave Polygon\") +\n  theme_solid() +\n  theme(\n    plot.title = element_text(size = 20),\n    plot.title.position = \"plot\"\n  )\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/swiftly-cleaning-1.png){width=672}\n:::\n\n```{.r .cell-code}\njun2025_reference_week %>%\n  count(routeId)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 2\n  routeId      n\n  <chr>    <int>\n1 AS      121703\n2 ER      189153\n3 GI        9921\n4 RW      152398\n5 SB      129553\n6 SG      118302\n7 SV      130208\n```\n\n\n:::\n:::\n\n\n### OTP by Direction\n\nThis chunk computes on-time performance by direction (NB or SB), filtering to excessively late records. Northbound and southbound trips comprise roughly the same share of all trips; however, the higher number of excessively late southbound data points could be indicative of other issues.\n\n\n::: {.cell}\n\n```{.r .cell-code}\njun2025_reference_week_dir <- jun2025_reference_week %>%\n  select(dailyTrip, directionId, OTP, routeId) %>%\n  filter(OTP == \"Excessively Late\")\n\njun2025_reference_week_dir %>%\n  count(directionId)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  directionId     n\n  <chr>       <int>\n1 NB          12069\n2 SB          13488\n```\n\n\n:::\n\n```{.r .cell-code}\njun2025_reference_week_dir %>%\n  count(directionId, routeId)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 3\n   directionId routeId     n\n   <chr>       <chr>   <int>\n 1 NB          AS         51\n 2 NB          ER       2182\n 3 NB          GI         58\n 4 NB          RW       8300\n 5 NB          SB        671\n 6 NB          SG          5\n 7 NB          SV        802\n 8 SB          AS        472\n 9 SB          ER       4569\n10 SB          RW       6040\n11 SB          SB        696\n12 SB          SV       1711\n```\n\n\n:::\n:::\n\n\n### Bar Charts\n\nThe bar charts below visualize key engineered features. The first chart shows the distribution of excessively late trips by the time spent excessively late (as a percentage of total data points per trip).\n\nThree key takeaways from the second plot:\n\n1. Even though weekdays account for the majority of data points, they account for under half of excessively late data points. Weekend service is the only category where excessively late counts surpass non-excessively late counts.\n2. Nearly 80 percent of excessively late data points are attributed to the East River and Rockaway routes.\n3. The PM peak period (approximately 1pm to 10pm) accounts for the overwhelming majority of problematic data points.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexcessivelyLatePlotVariables <-\n  jun2025_reference_week %>%\n  as.data.frame() %>%\n  select(excessivelyLate, dayOfWeek, routeId, timeOfDay, blockId, directionId, firstRecordLate) %>%\n  gather(variable, value, -excessivelyLate) %>%\n  filter(!is.na(value))\n\njun2025_reference_week_wide <- jun2025_reference_week %>%\n  count(key_identifier, OTP) %>%\n  pivot_wider(\n    names_from = OTP,\n    values_from = n,\n    values_fill = 0\n  ) %>%\n  mutate(Total = rowSums(across(-key_identifier)))\n\njun2025_reference_week_wide\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2,133 × 6\n   key_identifier                   Early Ontime  Late `Excessively Late` Total\n   <chr>                            <int>  <int> <int>              <int> <dbl>\n 1 2025-06-16 11 ER 1220 NB Weekday    72    129     0                  0   201\n 2 2025-06-16 11 ER 1224 NB Weekday   191    189     0                  0   380\n 3 2025-06-16 11 ER 1257 SB Weekday   260    210    28                  0   498\n 4 2025-06-16 11 ER 4104 NB Weekday    86    309     0                  0   395\n 5 2025-06-16 11 ER 4109 NB Weekday    24    223     0                  0   247\n 6 2025-06-16 11 ER 4113 NB Weekday    52    330     0                  0   382\n 7 2025-06-16 11 ER 4116 NB Weekday    19    265    25                  0   309\n 8 2025-06-16 11 ER 4119 NB Weekday    85    217     0                  0   302\n 9 2025-06-16 11 ER 4123 NB Weekday     0    116   166                 24   306\n10 2025-06-16 11 ER 4128 NB Weekday     0     32    30                293   355\n# ℹ 2,123 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\njun2025_reference_week_percents <- jun2025_reference_week_wide %>%\n  mutate(round(across(-c(key_identifier, Total), ~ . / Total * 100), 2)) %>%\n  pivot_longer(\n    cols = -c(key_identifier, Total),\n    names_to = \"OTP\",\n    values_to = \"Percent\"\n  ) %>%\n  filter(OTP == \"Excessively Late\", Percent > 0) %>%\n  mutate(Percent_Rounded = round(Percent, 0))\n\nmean_val <- mean(jun2025_reference_week_percents$Percent_Rounded)\nmedian_val <- median(jun2025_reference_week_percents$Percent_Rounded)\n\nggplot() +\n  geom_histogram(data = jun2025_reference_week_percents, color = \"white\", fill = \"#006bb6\", linewidth = 0.3, aes(x = Percent_Rounded), binwidth = 10) +\n  geom_vline(xintercept = mean_val, color = \"red2\", linetype = \"dashed\", linewidth = 1) +\n  geom_vline(xintercept = median_val, color = \"darkgreen\", linetype = \"dashed\", linewidth = 1) +\n  annotate(\"text\", x = mean_val, y = 15, label = \"Mean\", color = \"red2\", angle = 90, vjust = -0.5) +\n  annotate(\"text\", x = median_val, y = 15, label = \"Median\", color = \"darkgreen\", angle = 90, vjust = -0.5) +\n  labs(\n    title = \"Distribution of Excessively Late Trips by Time Spent Excessively Late\",\n    x = \"Percent\",\n    y = \"Count\"\n  ) +\n  theme_excel_new() +\n  theme(\n    axis.title = element_text(size = 14),\n    plot.title = element_text(size = 20),\n    plot.subtitle = element_text(size = 16),\n    plot.title.position = \"plot\"\n  )\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/swiftly-bar-charts-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplot_df <- excessivelyLatePlotVariables %>%\n  group_by(excessivelyLate, variable, value) %>%\n  summarise(count = n(), .groups = \"drop\") %>%\n  group_by(excessivelyLate, variable) %>%\n  mutate(prop = count / sum(count)) %>%\n  ungroup()\n\nggplot(plot_df, aes(x = ifelse(variable == \"timeOfDay\", as.numeric(value), value),\n                    y = prop, fill = as.factor(excessivelyLate))) +\n  geom_col(position = \"dodge\") +\n  facet_wrap(~ variable, scales = \"free_x\") +\n  scale_y_continuous(labels = scales::percent) +\n  scale_fill_manual(values = c(\"0\" = \"limegreen\", \"1\" = \"darkred\"),\n                    labels = c(\"Not Excessively Late\", \"Excessively Late\"),\n                    name = \"\") +\n  labs(x = NULL, y = \"Percent within group\") +\n  theme_excel_new()\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/swiftly-bar-charts-2.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\njun2025_reference_week <- jun2025_reference_week %>%\n  mutate(day_route = paste(dayOfWeek, routeId, sep = \" \"))\n\nspeed_by_route <- jun2025_reference_week %>%\n  group_by(day_route, dayOfWeek, routeId) %>%\n  summarise(\n    avgKnots = mean(knots, na.rm = TRUE),\n    medKnots = median(knots, na.rm = TRUE),\n    n = dplyr::n(),\n    .groups = \"drop\"\n  )\n\nggplot() +\n  geom_col(data = speed_by_route, aes(x = day_route, y = avgKnots, fill = dayOfWeek)) +\n  labs(\n    title = \"Average Speed by Route and Service Level\",\n    x = \"Service Level\",\n    y = \"Average Knots\"\n  ) +\n  scale_fill_manual(\n    values = c(\n      \"Holiday\" = \"limegreen\",\n      \"Weekday\" = \"#006bb6\",\n      \"Weekend\" = \"darkred\"\n    )\n  ) +\n  theme_excel_new() +\n  theme(\n    plot.title = element_text(size = 20),\n    plot.subtitle = element_text(size = 16),\n    plot.title.position = \"plot\",\n    axis.text.x = element_text(angle = 45, hjust = 1)\n  )\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/swiftly-bar-chart-by-route-1.png){width=672}\n:::\n:::\n\n\n### Landings Map\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = boroughs, color = \"white\") +\n  geom_sf(data = landings, color = \"black\", size = 3) +\n  labs(title = \"NYC Ferry Landings\") +\n  theme_solid() +\n  theme(\n    plot.title = element_text(size = 16),\n    plot.title.position = \"plot\"\n  )\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/swiftly-landings-map-1.png){width=672}\n:::\n:::\n\n\n### Fishnet and Kernel Density\n\nSince these datasets contain thousands of points per day, aggregation is the most efficient way to process and observe the data. A fishnet was created using a grid cell side of 250 meters. The figure represents the data for the sample week, excluding any grid cell with a density of 0.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfishnet_swiftly <-\n  st_make_grid(water, cellsize = 250) %>%\n  st_sf() %>%\n  mutate(uniqueID = rownames(.))\n\njun2025_net <- st_join(\n  fishnet_swiftly, jun2025_reference_week_excessively_lates_sf, join = st_intersects) %>%\n  group_by(uniqueID) %>%\n  summarise(mean_speed = mean(knots, na.rm = TRUE),\n            n = n(), .groups = \"drop\") %>%\n  filter(!is.na(mean_speed))\n\njun2025_ppp <- as.ppp(st_coordinates(jun2025_reference_week_excessively_lates_sf), W = st_bbox(jun2025_net))\njun2025_KD <- density.ppp(jun2025_ppp, sigma = 1000)\n\nas.data.frame(jun2025_KD) %>%\n  st_as_sf(coords = c(\"x\", \"y\"), crs = st_crs(jun2025_net)) %>%\n  aggregate(., jun2025_net, mean) %>%\n  ggplot() +\n    geom_sf(aes(fill = value), color = NA, linewidth = 0) +\n    geom_sf(data = landings, color = \"black\", size = 1, alpha = 0.5) +\n    scale_fill_viridis(name = \"Density\") +\n    labs(title = \"Kernel Density of Excessively Late Data Points, 6/16/25 to 6/22/25\") +\n    theme_solid() +\n    theme(\n      plot.title = element_text(size = 16),\n      plot.title.position = \"plot\"\n    )\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/swiftly-fishnet-1.png){width=2100}\n:::\n:::\n\n\n### Mean Speed\n\nThe following figure shows the average speed of each data point in knots per grid cell, regardless of on-time performance designation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(jun2025_net) +\n  geom_sf(data = boroughs, color = \"white\") +\n  geom_sf(data = landings, color = \"black\", size = 2, alpha = 0.5) +\n  geom_sf(aes(fill = mean_speed), color = NA) +\n  coord_sf(\n    xlim = c(bbox_hull[\"xmin\"] - 100, bbox_hull[\"xmax\"] + 100),\n    ylim = c(bbox_hull[\"ymin\"] - 200, bbox_hull[\"ymax\"] + 200),\n    expand = FALSE\n  ) +\n  scale_fill_viridis_c(option = \"D\", name = \"Knots\") +\n  labs(title = \"Mean Vessel Speed by Cell\") +\n  theme_solid() +\n  theme(\n    plot.title = element_text(size = 16),\n    plot.title.position = \"plot\"\n  )\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/swiftly-mean-speed-1.png){width=672}\n:::\n:::\n\n\n### Kernel Density Plots — Hourly\n\nTo analyze how OTP changes spatially throughout the PM peak, kernel densities of excessively late data points were mapped for each hour between 1pm and 10pm.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmake_hourly_kd <- function(hour_val) {\n  net <- st_join(fishnet_swiftly, jun2025_reference_week_excessively_lates_sf, join = st_intersects) %>%\n    group_by(uniqueID) %>%\n    filter(hour == hour_val) %>%\n    summarise(mean_speed = mean(knots, na.rm = TRUE), n = n(), .groups = \"drop\")\n  kd <- density.ppp(as.ppp(st_coordinates(net), W = st_bbox(jun2025_net)), sigma = 1000)\n  kd\n}\n\nkd_list <- list(\n  '1PM'  = make_hourly_kd(\"13\"),\n  '2PM'  = make_hourly_kd(\"14\"),\n  '3PM'  = make_hourly_kd(\"15\"),\n  '4PM'  = make_hourly_kd(\"16\"),\n  '5PM'  = make_hourly_kd(\"17\"),\n  '6PM'  = make_hourly_kd(\"18\"),\n  '7PM'  = make_hourly_kd(\"19\"),\n  '8PM'  = make_hourly_kd(\"20\"),\n  '9PM'  = make_hourly_kd(\"21\"),\n  '10PM' = make_hourly_kd(\"22\")\n)\n\nall_values <- unlist(lapply(kd_list, \\(kd) as.data.frame(kd)$value))\nglobal_limits <- range(all_values, na.rm = TRUE)\n\nplots <- imap(kd_list, ~{\n  sf_pts <- st_as_sf(as.data.frame(.x), coords = c(\"x\", \"y\"), crs = st_crs(jun2025_net))\n  agg <- aggregate(sf_pts[\"value\"], jun2025_net, mean, na.rm = TRUE)\n\n  ggplot() +\n    geom_sf(data = boroughs, color = \"white\") +\n    geom_sf(data = agg, aes(fill = value), color = NA, linewidth = 0) +\n    coord_sf(\n      xlim = c(bbox_hull[\"xmin\"] - 100, bbox_hull[\"xmax\"] + 100),\n      ylim = c(bbox_hull[\"ymin\"] - 100, bbox_hull[\"ymax\"] + 100),\n      expand = FALSE\n    ) +\n    scale_fill_viridis_c(name = \"Kernel Density\", limits = global_limits, oob = scales::squish) +\n    labs(title = paste(\"KD -\", .y)) +\n    theme_solid() +\n    theme(\n      plot.title = element_text(size = 12),\n      plot.title.position = \"plot\"\n    )\n})\n\nwrap_plots(plots, ncol = 5) +\n  plot_layout(guides = \"collect\") +\n  plot_annotation(\n    title = \"Excessively Late Across TOD\",\n    caption = \"Unified KD Scale, 250m Grid Cell Size\"\n  ) &\n  theme(\n    legend.position = \"right\",\n    legend.box = \"horizontal\",\n    plot.margin = margin(1, 1, 1, 1)\n  )\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/swiftly-kds-1.png){width=2100}\n:::\n:::\n\n\nOne potentially useful consideration is to observe locations where trips change OTP status. The following figure includes only instances where OTP status changes to either late or excessively late.\n\n\n::: {.cell}\n\n```{.r .cell-code}\njun2025_reference_week_late_sf <- jun2025_reference_week_sf %>%\n  filter(OTP_transition %in% c(\"Early -> Late\", \"Late -> Excessively Late\",\n                                \"Ontime -> Late\", \"Ontime -> Excessively Late\"))\n\nggplot() +\n  geom_sf(data = boroughs, color = \"white\") +\n  geom_sf(data = landings, color = \"black\", size = 2, alpha = 0.2) +\n  geom_sf(data = jun2025_reference_week_late_sf,\n          aes(color = OTP_transition), size = 2, alpha = 0.2) +\n  coord_sf(\n    xlim = c(bbox_east_river[\"xmin\"] - 10000, bbox_east_river[\"xmax\"] + 10000),\n    ylim = c(bbox_east_river[\"ymin\"] - 10000, bbox_east_river[\"ymax\"] + 10000),\n    expand = FALSE\n  ) +\n  labs(title = \"OTP Transition Locations\") +\n  scale_color_manual(\n    name = \"Transition Type\",\n    values = c(\n      \"Early -> Late\"               = \"#1e3888\",\n      \"Ontime -> Late\"              = \"#47a8bd\",\n      \"Ontime -> Excessively Late\"  = \"#ffad69\",\n      \"Late -> Excessively Late\"    = \"#9c3848\"\n    ),\n    labels = c(\n      \"Early -> Late\"               = \"Early to Late\",\n      \"Ontime -> Late\"              = \"Ontime to Late\",\n      \"Ontime -> Excessively Late\"  = \"Ontime to Excessively Late\",\n      \"Late -> Excessively Late\"    = \"Late to Excessively Late\"\n    )\n  ) +\n  facet_wrap(~OTP_transition) +\n  theme_solid() +\n  theme(\n    plot.title = element_text(size = 20),\n    plot.title.position = \"plot\"\n  )\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/swiftly-otp-transitions-1.png){width=672}\n:::\n:::\n\n\n### Leaflet Distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlandings_buffers_100ft <- st_buffer(landings, dist = 30.48)\ncounts <- lengths(st_intersects(landings_buffers_100ft, jun2025_reference_week_excessively_lates_sf))\nlandings_buffers_100ft$record_count <- counts\n\npoints_plot  <- st_transform(landings, 4326)\nbuffers_plot <- st_transform(landings_buffers_100ft, 4326)\nroutes_plot  <- st_transform(routes, 4326)\nboroughs_plot <- st_transform(boroughs, 4326)\n\njun2025_reference_week_elate_sf <- jun2025_reference_week_sf %>%\n  filter(OTP == \"Excessively Late\") %>%\n  st_transform(4326)\n\njun2025_reference_week_not_elate_sf <- jun2025_reference_week_sf %>%\n  filter(OTP != \"Excessively Late\") %>%\n  st_transform(4326)\n\nleaflet() %>%\n  addProviderTiles(\"Esri.WorldImagery\", group = \"Imagery\",\n                   options = tileOptions(opacity = 0.6)) %>%\n  addPolygons(data = boroughs_plot, color = \"#828282\", weight = 1, fillOpacity = 0.75, group = \"Boroughs\") %>%\n  addPolylines(data = routes_plot, color = \"#006bb6\", weight = 2, opacity = 0.2, group = \"Routes\") %>%\n  addPolygons(data = buffers_plot, color = \"#f58426\", weight = 10, fillOpacity = 0.75, group = \"Landings\",\n              label = ~paste0(\"Records: \", record_count)) %>%\n  addCircleMarkers(data = points_plot, radius = 3, color = \"#f58426\", opacity = 0.6, group = \"Landings\") %>%\n  addCircleMarkers(data = jun2025_reference_week_elate_sf, radius = 0.5, color = \"#47a8bd\",\n    opacity = 0.6, fillOpacity = 0.4, group = \"Excessively Late\",\n    label = ~paste0(\"Speed: \", round(knots, 2)),\n    popup = ~paste0(\"<b>Speed:</b> \", round(knots, 2), \" knots\",\n                    \"<br><b>Route:</b> \", routeId,\n                    \"<br><b>Trip:</b> \", tripId,\n                    \"<br><b>Vessel:</b> \", vehicleId,\n                    \"<br><b>Time:</b> \", time)) %>%\n  addCircleMarkers(data = jun2025_reference_week_not_elate_sf, radius = 0.5, color = \"#9c3848\",\n    opacity = 0.6, fillOpacity = 0.4, group = \"Not Excessively Late\",\n    label = ~paste0(\"Speed: \", round(knots, 2)),\n    popup = ~paste0(\"<b>Speed:</b> \", round(knots, 2), \" knots\",\n                    \"<br><b>Route:</b> \", routeId,\n                    \"<br><b>Trip:</b> \", tripId,\n                    \"<br><b>Vessel:</b> \", vehicleId,\n                    \"<br><b>Time:</b> \", time)) %>%\n  addLayersControl(\n    overlayGroups = c(\"Boroughs\", \"Routes\", \"Landings\", \"Excessively Late\", \"Not Excessively Late\"),\n    baseGroups = c(\"Imagery\"),\n    options = layersControlOptions(collapsed = FALSE)\n  )\n```\n:::\n\n\nThis Leaflet map shows the data with an imagery layer for context. For the sake of processing power, the results are not shown by default — remove the `eval: false` chunk option to render it.\n\n\n\n# Modeling\n\n## Associative Model\n**By: Yiming 'Ming' Cao**\n\n### Objective and Design\n\nThis section presents an associative model for explaining stop-level arrival lateness in the NYC Ferry system. The goal is interpretation rather than advance prediction. Instead of asking only whether a future trip will be delayed, this model asks which historical factors are associated with observed delay patterns.\n\nThe unit of analysis is a stop-level observation. The dependent variable is arrival lateness in minutes relative to the original schedule. Predictors are organized into five explanatory domains: structural context, environmental conditions, temporal patterns, operational propagation, and vessel characteristics.\n\nThis grouped design allows us to compare how different types of factors contribute to delay variation while keeping the final model interpretable for operational use.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(7900)\n\ninput_parquet <- \"../exploratory_code/modeling/associative/baseline_modeling_table_final_direct.parquet\"\noutcome_cont  <- \"lateness_vs_original_schedule_min\"\n\nweek_window_days <- 3\n\ncandidate_predictors <- c(\n  \"route_id\", \"direction\", \"stop_sequence\", \"prev_stop_sched_hour\", \"prev_stop_sched_hour_group\",\n  \"schedule_season\", \"schedule_daytype\", \"vessel_trip_seq_in_chain\", \"vessel_capacity\",\n  \"is_terminal_stop\", \"prev_stop_shared_stop_flag\", \"curr_stop_shared_stop_flag\",\n  \"planned_turnaround_gap_min\", \"scheduled_headway_min\", \"expected_water_min\",\n  \"prev_stop_sequence\", \"prev_stop_boardings\", \"prev_stop_alightings\", \"prev_stop_onboard\",\n  \"prev_stop_load_factor\", \"env_temperature_c\", \"env_wind_speed_mps\", \"env_visibility_m\",\n  \"env_precipitation_mm\", \"env_battery_water_level_anomaly\", \"env_narrows_current_residual\",\n  \"env_battery_water_level_obs\", \"env_narrows_current_obs\"\n)\nprior_delay_predictors <- c(\"inherited_prev_trip_delay\", \"carried_within_trip_delay\")\n```\n:::\n\n\n### Data Scope\n\nThe model uses the stop-level baseline modeling table as its input dataset. After loading the data, we confirmed the number of records and the availability of candidate predictors before fitting the associative models.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!file.exists(input_parquet)) stop(\"Missing input parquet: \", input_parquet)\ndf_raw <- read_parquet(input_parquet) %>% as_tibble()\n\ndf <- df_raw %>%\n  mutate(\n    trip_date = as.Date(substr(as.character(trip_key), 1, 8), format = \"%Y%m%d\")\n  )\n\npredictors_no_prior   <- intersect(candidate_predictors, names(df))\npredictors_with_prior <- unique(c(predictors_no_prior, intersect(prior_delay_predictors, names(df))))\n\ntibble(\n  input_rows              = nrow(df_raw),\n  rows_after_load         = nrow(df),\n  predictors_no_prior_n   = length(predictors_no_prior),\n  predictors_with_prior_n = length(predictors_with_prior)\n) %>% kable(caption = \"Data Scope and Predictor Availability\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Data Scope and Predictor Availability\n\n| input_rows| rows_after_load| predictors_no_prior_n| predictors_with_prior_n|\n|----------:|---------------:|---------------------:|-----------------------:|\n|     613071|          613071|                    28|                      30|\n\n\n:::\n:::\n\n\n### Predictor Domains\n\nTo support interpretation, predictors in the associative model were organized into five explanatory domains. This grouped structure separates baseline route and stop context from environmental conditions, temporal patterns, operational propagation, and vessel-related characteristics. The goal is to interpret delay association at the domain level rather than focusing only on isolated individual coefficients.\n\n#### Domain A: Structural Context\n\nThe structural domain captures baseline differences in how delay varies across the ferry network. These predictors describe route, stop position, and stop-context features that reflect how service is organized spatially and operationally. Variables in this domain include route and direction identifiers, stop sequence, terminal status, and shared-stop context. We interpret this domain as representing the structural baseline of delay rather than short-term changing conditions.\n\n#### Domain B: Environmental Conditions\n\nThe environmental domain captures external natural conditions that may affect vessel movement and docking performance. These predictors include weather and water-related variables such as temperature, wind speed, visibility, precipitation, water-level, and current-related measures. This domain is especially important for the client because it helps distinguish external operating conditions from delay that is simply inherited from earlier parts of the trip.\n\n#### Domain C: Temporal Patterns\n\nThe temporal domain captures recurring calendar and time-of-day structure in delay. These predictors describe when service occurs rather than where it occurs or what the vessel has already experienced. Variables in this domain include scheduled hour, scheduled hour group, day type, and season. We use this domain to represent regular service rhythms such as weekday versus weekend patterns, seasonal demand differences, and time-of-day effects.\n\n#### Domain D: Operational Propagation\n\nThe operational propagation domain captures delay carried forward through the operating chain. These predictors reflect whether lateness has already accumulated earlier in the trip or in a prior linked trip on the same vessel. Variables in this domain include inherited previous-trip delay and carried within-trip delay. This domain is operationally meaningful, but it is interpreted as one component of the associative model rather than the sole basis for explaining delay.\n\n#### Domain E: Vessel Characteristics\n\nThe vessel domain captures systematic differences associated with vessel capacity and operating role. These predictors help assess whether some delay patterns are associated with the characteristics of the vessel being used rather than only with route structure or environmental conditions. Variables in this domain include vessel capacity and related vessel-level operational identifiers retained in the final specification.\n\n### Data Preparation\n\nBefore model estimation, the stop-level modeling table was prepared to support a consistent and interpretable associative model. This section summarizes the key preparation steps: variable construction, missing-value treatment for environmental fields, and helper functions used for model fitting and summary extraction.\n\n#### Data Cleaning and Variable Construction\n\nThe input table was converted into a stop-level analytic dataset. We created a trip date field from the trip identifier, checked which candidate predictors were available, and retained variables needed for the outcome and domain-based model structure.\n\n#### Environmental Variable Imputation\n\nMissing environmental values were imputed using a local time-slot rolling rule. The primary fill used observations from the same scheduled hour within a centered seven-day window around the trip date. If no value was available, the method fell back to the same scheduled hour group within the same centered window.\n\nThis approach keeps environmental predictors in the model without relying only on complete-case filtering. It also keeps the imputed values tied to nearby dates and comparable operating periods.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbuild_week_fill_map <- function(day_slot_tbl, group_col, date_col = \"trip_date\", value_col = \"slot_day_median\", window_days = 3) {\n  if (nrow(day_slot_tbl) == 0) return(tibble())\n  split_tbl <- split(day_slot_tbl, day_slot_tbl[[group_col]], drop = TRUE)\n  out <- lapply(split_tbl, function(gdf) {\n    gdf <- gdf[order(gdf[[date_col]]), , drop = FALSE]\n    d <- gdf[[date_col]]\n    v <- gdf[[value_col]]\n    week_fill <- vapply(seq_along(v), function(i) {\n      idx <- abs(as.integer(d - d[i])) <= window_days\n      val <- suppressWarnings(median(v[idx], na.rm = TRUE))\n      ifelse(is.finite(val), val, NA_real_)\n    }, numeric(1))\n    gdf$week_fill <- week_fill\n    gdf[, c(group_col, date_col, \"week_fill\"), drop = FALSE]\n  })\n  bind_rows(out)\n}\n\nimpute_by_local_slot_week <- function(data, var_name, window_days = 3) {\n  x <- data\n  miss_before <- sum(is.na(x[[var_name]]))\n  if (miss_before == 0) {\n    return(list(data = x, summary = tibble(variable = var_name, n_missing_before = 0L, n_filled_primary = 0L, n_filled_fallback = 0L, n_missing_after = 0L)))\n  }\n\n  primary_daily <- x %>%\n    filter(!is.na(.data[[var_name]]), !is.na(trip_date), !is.na(prev_stop_sched_hour)) %>%\n    group_by(prev_stop_sched_hour, trip_date) %>%\n    summarise(slot_day_median = median(.data[[var_name]], na.rm = TRUE), .groups = \"drop\")\n  primary_fill <- build_week_fill_map(primary_daily, group_col = \"prev_stop_sched_hour\", value_col = \"slot_day_median\", window_days = window_days) %>%\n    rename(fill_primary = week_fill)\n\n  fallback_daily <- x %>%\n    filter(!is.na(.data[[var_name]]), !is.na(trip_date), !is.na(prev_stop_sched_hour_group)) %>%\n    group_by(prev_stop_sched_hour_group, trip_date) %>%\n    summarise(slot_day_median = median(.data[[var_name]], na.rm = TRUE), .groups = \"drop\")\n  fallback_fill <- build_week_fill_map(fallback_daily, group_col = \"prev_stop_sched_hour_group\", value_col = \"slot_day_median\", window_days = window_days) %>%\n    rename(fill_fallback = week_fill)\n\n  x <- x %>%\n    left_join(primary_fill, by = c(\"prev_stop_sched_hour\", \"trip_date\")) %>%\n    left_join(fallback_fill, by = c(\"prev_stop_sched_hour_group\", \"trip_date\"))\n\n  was_missing      <- is.na(x[[var_name]])\n  fill_primary_idx  <- was_missing & !is.na(x$fill_primary)\n  fill_fallback_idx <- was_missing & is.na(x$fill_primary) & !is.na(x$fill_fallback)\n\n  x[[var_name]][fill_primary_idx]  <- x$fill_primary[fill_primary_idx]\n  x[[var_name]][fill_fallback_idx] <- x$fill_fallback[fill_fallback_idx]\n  x <- x %>% select(-fill_primary, -fill_fallback)\n\n  list(\n    data = x,\n    summary = tibble(\n      variable          = var_name,\n      n_missing_before  = miss_before,\n      n_filled_primary  = sum(fill_primary_idx, na.rm = TRUE),\n      n_filled_fallback = sum(fill_fallback_idx, na.rm = TRUE),\n      n_missing_after   = sum(is.na(x[[var_name]]))\n    )\n  )\n}\n\nimpute_vars <- intersect(\n  c(\"env_temperature_c\", \"env_wind_speed_mps\", \"env_visibility_m\",\n    \"env_precipitation_mm\", \"env_narrows_current_residual\",\n    \"env_battery_water_level_obs\", \"env_narrows_current_obs\"),\n  names(df)\n)\n\nimpute_summary_list <- list()\ndf_imp <- df\nfor (v in impute_vars) {\n  res <- impute_by_local_slot_week(df_imp, v, window_days = week_window_days)\n  df_imp <- res$data\n  impute_summary_list[[length(impute_summary_list) + 1]] <- res$summary\n}\nimputation_summary <- bind_rows(impute_summary_list)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nimputation_summary %>%\n  mutate(\n    pct_missing_before = round(n_missing_before / nrow(df) * 100, 2),\n    pct_missing_after  = round(n_missing_after  / nrow(df_imp) * 100, 2)\n  ) %>%\n  kable(caption = \"Summary of Environmental Variable Imputation\", digits = 2)\n```\n\n::: {.cell-output-display}\n\n\nTable: Summary of Environmental Variable Imputation\n\n|variable                     | n_missing_before| n_filled_primary| n_filled_fallback| n_missing_after| pct_missing_before| pct_missing_after|\n|:----------------------------|----------------:|----------------:|-----------------:|---------------:|------------------:|-----------------:|\n|env_temperature_c            |              482|                0|               283|             199|               0.08|              0.03|\n|env_wind_speed_mps           |             1116|                0|               917|             199|               0.18|              0.03|\n|env_visibility_m             |              567|                0|               368|             199|               0.09|              0.03|\n|env_precipitation_mm         |              373|                0|               174|             199|               0.06|              0.03|\n|env_narrows_current_residual |            52071|                0|             48636|            3435|               8.49|              0.56|\n|env_battery_water_level_obs  |              373|                0|               174|             199|               0.06|              0.03|\n|env_narrows_current_obs      |            52071|                0|             48636|            3435|               8.49|              0.56|\n\n\n:::\n:::\n\n\n#### Modeling Utilities\n\nA small set of reusable helper functions was created to prepare model inputs, fit linear models, extract model metrics, and generate standardized coefficient summaries.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprepare_model_df <- function(data, outcome, predictors) {\n  data %>% select(all_of(c(outcome, predictors))) %>% drop_na()\n}\n\nfit_linear <- function(data, model_name, outcome, predictors) {\n  d   <- prepare_model_df(data, outcome, predictors)\n  fml <- as.formula(paste(outcome, \"~\", paste(predictors, collapse = \" + \")))\n  fit <- lm(fml, data = d)\n  pred <- predict(fit, newdata = d)\n  rmse <- sqrt(mean((d[[outcome]] - pred)^2))\n  g    <- glance(fit)\n\n  list(\n    metrics = tibble(\n      model_name  = model_name, model_type = \"linear\",\n      n = nrow(d), aic = g$AIC, bic = g$BIC,\n      rsq = g$r.squared, adj_rsq = g$adj.r.squared, rmse = rmse,\n      pseudo_rsq = NA_real_, accuracy = NA_real_,\n      sensitivity = NA_real_, specificity = NA_real_, auc = NA_real_\n    ),\n    coefs        = tidy(fit) %>% mutate(model_name = model_name, model_type = \"linear\"),\n    formula_text = paste(deparse(fml), collapse = \"\")\n  )\n}\n\nstandardize_for_lm <- function(data, outcome, predictors) {\n  d       <- data %>% select(all_of(c(outcome, predictors))) %>% drop_na()\n  num_vars <- names(d)[sapply(d, is.numeric)]\n  d %>% mutate(across(all_of(num_vars), ~ as.numeric(scale(.x))))\n}\n\nfit_standardized_linear <- function(data, model_name, outcome, predictors) {\n  d_std <- standardize_for_lm(data, outcome, predictors)\n  fml   <- as.formula(paste(outcome, \"~\", paste(predictors, collapse = \" + \")))\n  fit   <- lm(fml, data = d_std)\n  broom::tidy(fit) %>%\n    filter(term != \"(Intercept)\") %>%\n    mutate(model_name = model_name, abs_estimate = abs(estimate)) %>%\n    arrange(desc(abs_estimate))\n}\n```\n:::\n\n\n### Variable Screening and Final Specification\n\nThis section explains how the final associative-model specification was selected from the broader predictor pool. The goal was not to include every available variable, but to keep interpretable coverage across the five explanatory domains while reducing redundancy among closely related predictors.\n\n#### Initial Candidate Variables\n\nThe initial predictor pool was intentionally broad so that each explanatory domain was represented. Candidate variables included route and stop structure, environmental conditions, temporal indicators, operational propagation terms, and vessel/load-related characteristics. This broader pool provided the starting point for a smaller, more interpretable final specification.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndomain_a_predictors <- intersect(c(\n  \"route_id\", \"direction\", \"stop_sequence\", \"is_terminal_stop\",\n  \"prev_stop_shared_stop_flag\", \"curr_stop_shared_stop_flag\"\n), names(df_imp))\n\ndomain_b_predictors <- intersect(c(\n  \"env_temperature_c\", \"env_wind_speed_mps\", \"env_visibility_m\",\n  \"env_precipitation_mm\", \"env_narrows_current_residual\",\n  \"env_battery_water_level_obs\", \"env_narrows_current_obs\"\n), names(df_imp))\n\ndomain_c_predictors <- intersect(c(\n  \"prev_stop_sched_hour\", \"schedule_season\", \"schedule_daytype\"\n), names(df_imp))\n\ndomain_d_predictors <- intersect(c(\n  \"inherited_prev_trip_delay\", \"carried_within_trip_delay\"\n), names(df_imp))\n\ndomain_e_predictors <- intersect(c(\n  \"vessel_capacity\", \"vessel_trip_seq_in_chain\",\n  \"prev_stop_boardings\", \"prev_stop_alightings\",\n  \"prev_stop_onboard\", \"prev_stop_load_factor\"\n), names(df_imp))\n\nfinal_predictors <- unique(c(\n  domain_a_predictors, domain_b_predictors,\n  domain_c_predictors, domain_d_predictors, domain_e_predictors\n))\n```\n:::\n\n\n#### Redundancy and Multicollinearity Checks\n\nBecause several candidate predictors measured closely related aspects of stop position, ridership, and operating context, we reviewed pairwise correlations among numeric predictors before fitting the final associative model. The goal was not to eliminate all correlation, but to identify clusters of variables that conveyed largely overlapping information and would make coefficient interpretation less clear.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnumeric_candidate_predictors <- intersect(\n  candidate_predictors,\n  names(df_imp)[sapply(df_imp, is.numeric)]\n)\n\ncorr_vars   <- df_imp %>%\n  select(all_of(numeric_candidate_predictors)) %>%\n  select(where(~ !all(is.na(.))))\n\ncorr_matrix <- cor(corr_vars, use = \"pairwise.complete.obs\")\n```\n:::\n\n\nThe figure below highlights selected variables reviewed during specification design. These variables are related to stop position and previous-stop load conditions, so they were checked carefully before finalizing the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfocus_vars <- c(\"stop_sequence\", \"prev_stop_sequence\", \"prev_stop_onboard\", \"prev_stop_load_factor\")\nfocus_corr <- corr_matrix[focus_vars, focus_vars]\n\nas.data.frame(as.table(focus_corr)) %>%\n  rename(var1 = Var1, var2 = Var2, corr = Freq) %>%\n  mutate(label = ifelse(var1 == var2, \"\", sprintf(\"%.2f\", corr))) %>%\n  ggplot(aes(x = var1, y = var2, fill = corr)) +\n  geom_tile(color = \"white\", linewidth = 0.5) +\n  geom_text(aes(label = label), size = 4) +\n  scale_fill_gradient2(low = \"#1A9988\", mid = \"white\", high = \"#EB5600\", midpoint = 0, limits = c(-1, 1)) +\n  coord_fixed() +\n  theme_minimal() +\n  theme(\n    panel.grid = element_blank(),\n    axis.text.x = element_text(angle = 45, hjust = 1),\n    plot.title = element_text(size = 13, face = \"bold\", hjust = 0.5)\n  ) +\n  labs(title = \"Correlation Among Selected Candidate Predictors\", x = NULL, y = NULL, fill = \"Correlation\")\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/ming-corr-plot-1.png){width=576}\n:::\n:::\n\n\nTo support specification decisions more systematically, we also identified highly correlated numeric predictor pairs using an absolute correlation threshold of 0.7.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nas.data.frame(as.table(corr_matrix)) %>%\n  rename(var1 = Var1, var2 = Var2, corr = Freq) %>%\n  filter(var1 != var2) %>%\n  mutate(abs_corr = abs(corr)) %>%\n  filter(abs_corr >= 0.7) %>%\n  rowwise() %>%\n  mutate(pair_id = paste(sort(c(var1, var2)), collapse = \" || \")) %>%\n  ungroup() %>%\n  distinct(pair_id, .keep_all = TRUE) %>%\n  arrange(desc(abs_corr)) %>%\n  select(var1, var2, corr, abs_corr) %>%\n  head(10) %>%\n  kable(caption = \"Highly correlated candidate predictor pairs (|r| >= 0.7)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Highly correlated candidate predictor pairs (|r| >= 0.7)\n\n|var1                  |var2              |      corr|  abs_corr|\n|:---------------------|:-----------------|---------:|---------:|\n|prev_stop_sequence    |stop_sequence     | 1.0000000| 1.0000000|\n|prev_stop_load_factor |prev_stop_onboard | 0.8965757| 0.8965757|\n\n\n:::\n:::\n\n\n#### Final Variable Set\n\nThe final variable set was selected to preserve coverage across the five explanatory domains while avoiding unnecessary duplication. When multiple variables represented similar information, we prioritized predictors that were easier to interpret operationally and more directly connected to the domain being represented.\n\nAfter reviewing correlation patterns, we removed redundant candidate variables and retained a reduced final specification for the combined associative model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfinal_predictors_trimmed <- setdiff(\n  final_predictors,\n  c(\"prev_stop_sequence\", \"prev_stop_sched_hour_group\")\n)\n\ntibble(\n  model        = \"Final combined associative model\",\n  n_predictors = length(final_predictors_trimmed)\n) %>% kable(caption = \"Predictor count in the final combined associative specification\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Predictor count in the final combined associative specification\n\n|model                            | n_predictors|\n|:--------------------------------|------------:|\n|Final combined associative model |           24|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_vif_model <- function(data, outcome, predictors) {\n  model_df <- data %>% select(all_of(unique(c(outcome, predictors)))) %>% drop_na()\n  lm(as.formula(paste(outcome, \"~\", paste(predictors, collapse = \" + \"))), data = model_df)\n}\n\nextract_vif_table <- function(model, model_name) {\n  vif_vals <- car::vif(model)\n  if (is.matrix(vif_vals)) {\n    out <- as.data.frame(vif_vals)\n    out$term <- rownames(out)\n    rownames(out) <- NULL\n    out$model <- model_name\n    out %>% rename(gvif = GVIF) %>%\n      mutate(adjusted_vif = gvif^(1 / (2 * Df))) %>%\n      select(model, term, Df, gvif, adjusted_vif)\n  } else {\n    tibble(model = model_name, term = names(vif_vals), vif = as.numeric(vif_vals)) %>%\n      arrange(desc(vif))\n  }\n}\n\nvif_model_final <- fit_vif_model(df_imp, outcome_cont, final_predictors_trimmed)\nvif_table_final <- extract_vif_table(vif_model_final, \"Final combined associative model\")\n```\n:::\n\n\nWe then checked variance inflation factors for the final combined specification. For multi-level categorical predictors, we report the adjusted GVIF, which is more comparable across terms with different degrees of freedom.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (\"adjusted_vif\" %in% names(vif_table_final)) {\n  vif_table_final %>%\n    arrange(desc(adjusted_vif)) %>%\n    head(10) %>%\n    mutate(gvif = round(gvif, 2), adjusted_vif = round(adjusted_vif, 2)) %>%\n    kable(caption = \"Top VIF results for the final combined associative specification\")\n} else {\n  vif_table_final %>%\n    arrange(desc(vif)) %>%\n    head(10) %>%\n    mutate(vif = round(vif, 2)) %>%\n    kable(caption = \"Top VIF results for the final combined associative specification\")\n}\n```\n\n::: {.cell-output-display}\n\n\nTable: Top VIF results for the final combined associative specification\n\n|model                            |term                         | Df|  gvif| adjusted_vif|\n|:--------------------------------|:----------------------------|--:|-----:|------------:|\n|Final combined associative model |prev_stop_onboard            |  1| 11.55|         3.40|\n|Final combined associative model |prev_stop_load_factor        |  1| 11.30|         3.36|\n|Final combined associative model |vessel_capacity              |  1|  4.37|         2.09|\n|Final combined associative model |env_temperature_c            |  1|  3.73|         1.93|\n|Final combined associative model |stop_sequence                |  1|  2.29|         1.51|\n|Final combined associative model |prev_stop_boardings          |  1|  2.22|         1.49|\n|Final combined associative model |is_terminal_stop             |  1|  1.77|         1.33|\n|Final combined associative model |prev_stop_alightings         |  1|  1.54|         1.24|\n|Final combined associative model |env_narrows_current_residual |  1|  1.54|         1.24|\n|Final combined associative model |env_narrows_current_obs      |  1|  1.51|         1.23|\n\n\n:::\n:::\n\n\n### Estimation Strategy\n\nThe associative model was estimated in two steps. First, we fit separate domain-specific linear models to summarize how much stop-level lateness was associated with each explanatory domain on its own. Second, we fit a combined associative model that included predictors from all five domains.\n\nTo make model comparisons more consistent, all models were estimated on the same analytic sample used for the final combined specification.\n\n#### Domain-Specific Models\n\nWe estimated separate linear models for the five explanatory domains: structural context, environmental conditions, temporal patterns, operational propagation, and vessel/load characteristics. Each model used the same dependent variable: stop-level arrival lateness in minutes.\n\nThese models were not treated as competing final models. Instead, they were used to compare the relative explanatory signal of each domain when considered separately.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_model <- df_imp %>%\n  drop_na(all_of(c(outcome_cont, final_predictors_trimmed)))\n\nmodel_results <- list(\n  domain_a_structural   = fit_linear(df_model, \"domain_a_structural\",   outcome_cont, domain_a_predictors),\n  domain_b_environment  = fit_linear(df_model, \"domain_b_environment\",  outcome_cont, domain_b_predictors),\n  domain_c_temporal     = fit_linear(df_model, \"domain_c_temporal\",     outcome_cont, domain_c_predictors),\n  domain_d_operational  = fit_linear(df_model, \"domain_d_operational\",  outcome_cont, domain_d_predictors),\n  domain_e_vessel       = fit_linear(df_model, \"domain_e_vessel\",       outcome_cont, domain_e_predictors),\n  combined_associative  = fit_linear(df_model, \"combined_associative\",  outcome_cont, final_predictors_trimmed)\n)\n```\n:::\n\n\n#### Combined Associative Model\n\nThe combined associative model uses the final predictor set across all five domains. This model serves as the main explanatory specification. It allows us to interpret individual coefficients while also discussing how different types of factors contribute to observed delay patterns within one framework.\n\n#### Comparison Logic\n\nModel comparison focused on interpretation rather than predictive model selection. We compared adjusted R-squared and RMSE across the domain-specific models and the combined model. The domain-specific models show how much delay variation is associated with each factor group on its own, while the combined model shows the explanatory power of the full specification.\n\n### Results: Explanatory Contribution by Domain\n\nThis section compares how much stop-level delay variation is explained by each explanatory domain. The goal is not to choose a predictive model, but to understand which types of factors are most strongly associated with observed lateness.\n\nThe domain-specific models show a clear hierarchy. Operational propagation explains the largest share of delay variation, followed by structural context. Environmental conditions, temporal patterns, and vessel/load characteristics explain smaller shares on their own, but they remain useful for interpretation because they describe monitorable operating conditions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_comparison_summary <- bind_rows(lapply(model_results, `[[`, \"metrics\")) %>%\n  mutate(\n    domain = dplyr::recode(\n      model_name,\n      combined_associative  = \"Combined Associative Model\",\n      domain_a_structural   = \"Domain A: Structural Context\",\n      domain_b_environment  = \"Domain B: Environmental Conditions\",\n      domain_c_temporal     = \"Domain C: Temporal Patterns\",\n      domain_d_operational  = \"Domain D: Operational Propagation\",\n      domain_e_vessel       = \"Domain E: Vessel / Load Characteristics\"\n    )\n  ) %>%\n  arrange(match(domain, c(\n    \"Domain A: Structural Context\", \"Domain B: Environmental Conditions\",\n    \"Domain C: Temporal Patterns\",  \"Domain D: Operational Propagation\",\n    \"Domain E: Vessel / Load Characteristics\", \"Combined Associative Model\"\n  )))\n\nmodel_comparison_summary %>%\n  select(domain, n, rsq, adj_rsq, rmse, aic, bic) %>%\n  mutate(across(c(rsq, adj_rsq, rmse), ~ round(.x, 4)),\n         across(c(aic, bic), ~ round(.x, 0))) %>%\n  kable(caption = \"Explained Variation by Domain and Final Combined Associative Model\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Explained Variation by Domain and Final Combined Associative Model\n\n|domain                                  |      n|    rsq| adj_rsq|   rmse|     aic|     bic|\n|:---------------------------------------|------:|------:|-------:|------:|-------:|-------:|\n|Domain A: Structural Context            | 592720| 0.1342|  0.1342| 3.6334| 3211498| 3211656|\n|Domain B: Environmental Conditions      | 592720| 0.0169|  0.0169| 3.8718| 3286834| 3286936|\n|Domain C: Temporal Patterns             | 592720| 0.0129|  0.0129| 3.8796| 3289224| 3289314|\n|Domain D: Operational Propagation       | 592720| 0.5865|  0.5865| 2.5109| 2773416| 2773461|\n|Domain E: Vessel / Load Characteristics | 592720| 0.0783|  0.0783| 3.7489| 3248611| 3248701|\n|Combined Associative Model              | 592720| 0.7413|  0.7412| 1.9863| 2495659| 2496054|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_comparison_summary %>%\n  filter(domain != \"Combined Associative Model\") %>%\n  mutate(domain = factor(domain, levels = domain), adj_rsq = round(adj_rsq, 4)) %>%\n  ggplot(aes(x = domain, y = adj_rsq)) +\n  geom_col(width = 0.65) +\n  geom_text(aes(label = round(adj_rsq, 3)), vjust = -0.3, size = 3.5) +\n  labs(title = \"Explanatory Contribution by Domain\", x = NULL, y = \"Adjusted R-squared\") +\n  theme_minimal(base_size = 12) +\n  theme(axis.text.x = element_text(angle = 25, hjust = 1), plot.title = element_text(face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/ming-domain-rsq-plot-1.png){width=768}\n:::\n:::\n\n\n#### Structural Context\n\nThe structural-context model explains a meaningful share of stop-level delay variation on its own. This indicates that route and stop configuration establish an important baseline pattern of delay across the system. In substantive terms, some portions of the ferry network appear structurally more delay-prone than others even before environmental or operational carry-forward effects are considered.\n\n#### Environmental Conditions\n\nThe environmental model explains a smaller share of total variation on its own. This does not mean environmental signals are unimportant. Instead, it suggests that weather and water conditions are secondary to propagated delay and structural context, while still offering useful monitorable signals for operational awareness.\n\n#### Temporal Patterns\n\nThe temporal model explains a modest share of variation, indicating that day type, scheduled hour, and season capture recurring service rhythms but do not dominate the delay process on their own. These results suggest that delay varies systematically across time, but those temporal patterns are weaker than operational propagation and structural context.\n\n#### Operational Propagation\n\nThe operational-propagation model explains the largest share of variation among the individual domains. This confirms that delay accumulation within and across trips is the strongest single explanatory component in the associative model. In other words, stop-level delay is highly path-dependent: once lateness has entered the operating chain, a substantial portion of subsequent delay can be understood as propagated rather than newly generated at each stop.\n\n#### Vessel / Load Characteristics\n\nThe vessel/load model explains the smallest share of variation among the five domains. This suggests that vessel capacity and load-related differences are present but relatively limited when considered in isolation. These factors are still useful as operational context, but they are secondary to route structure, external conditions, and propagated delay in explaining stop-level lateness.\n\n### Focused Interpretation of Key Predictors\n\nThe previous section compared explanatory contribution across domains. This section focuses on selected predictors used for coefficient interpretation and final presentation findings. These results are intended to make the model findings easier to interpret operationally, not to replace the full combined associative model.\n\n#### Focused Interpretive Specification\n\nIn addition to the full combined associative model, we estimated a smaller interpretive specification using predictors selected for coefficient interpretation. This focused model includes prior delay, route context, seasonal and day-type patterns, time bins, selected environmental conditions, and stop sequence.\n\nThis model is used to support coefficient interpretation in the final presentation. It should be read as a simplified interpretive view of the larger associative framework.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselected_predictors <- intersect(c(\n  \"inherited_prev_trip_delay\", \"route_id\", \"schedule_season\",\n  \"prev_stop_sched_hour_group\", \"schedule_daytype\",\n  \"env_temperature_c\", \"env_wind_speed_mps\", \"env_precipitation_mm\",\n  \"env_battery_water_level_obs\", \"stop_sequence\"\n), names(df_model))\n\nselected_model_df <- prepare_model_df(df_model, outcome_cont, selected_predictors)\n\nselected_formula <- as.formula(paste(\n  outcome_cont, \"~\",\n  paste(selected_predictors, collapse = \" + \"),\n  \"+ prev_stop_sched_hour_group:schedule_daytype\"\n))\n\nselected_fit <- lm(selected_formula, data = selected_model_df)\n\nbroom::glance(selected_fit) %>%\n  transmute(\n    model   = \"Focused interpretive specification\",\n    n       = nobs(selected_fit),\n    rsq     = round(r.squared, 4),\n    adj_rsq = round(adj.r.squared, 4),\n    rmse    = round(sqrt(mean(residuals(selected_fit)^2)), 4),\n    aic     = round(AIC(selected_fit), 0),\n    bic     = round(BIC(selected_fit), 0)\n  ) %>%\n  kable(caption = \"Focused Interpretive Specification Fit\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Focused Interpretive Specification Fit\n\n|model                              |      n|    rsq| adj_rsq|   rmse|     aic|     bic|\n|:----------------------------------|------:|------:|-------:|------:|-------:|-------:|\n|Focused interpretive specification | 592720| 0.4112|  0.4112| 2.9963| 2983010| 2983326|\n\n\n:::\n:::\n\n\n#### Raw Coefficient Interpretation\n\nTo support operational interpretation, we report raw coefficients from the focused interpretive specification. These coefficients show the estimated change in arrival lateness, in minutes, associated with each predictor while holding other variables in the model constant.\n\nFor numeric predictors, the coefficient is interpreted per one-unit increase. For categorical predictors, coefficients are interpreted relative to the reference category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbroom::tidy(selected_fit) %>%\n  filter(term != \"(Intercept)\") %>%\n  mutate(abs_estimate = abs(estimate)) %>%\n  arrange(desc(abs_estimate)) %>%\n  select(term, estimate, std.error, statistic, p.value) %>%\n  mutate(across(c(estimate, std.error), ~ round(.x, 4)),\n         statistic = round(statistic, 2),\n         p.value   = round(p.value, 4)) %>%\n  kable(caption = \"Raw Coefficients for Focused Interpretive Specification\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Raw Coefficients for Focused Interpretive Specification\n\n|term                                                    | estimate| std.error| statistic| p.value|\n|:-------------------------------------------------------|--------:|---------:|---------:|-------:|\n|route_idRW                                              |   3.2060|    0.0197|    162.75|  0.0000|\n|route_idGI                                              |   1.9491|    0.0762|     25.58|  0.0000|\n|route_idRR                                              |  -1.5515|    0.2317|     -6.70|  0.0000|\n|route_idSG                                              |   0.9711|    0.0167|     58.17|  0.0000|\n|inherited_prev_trip_delay                               |   0.8122|    0.0014|    561.44|  0.0000|\n|route_idSV                                              |   0.8064|    0.0132|     61.07|  0.0000|\n|prev_stop_sched_hour_group5_8:schedule_daytypeWEEKEND   |  -0.5679|    0.0451|    -12.59|  0.0000|\n|stop_sequence                                           |   0.5202|    0.0025|    208.73|  0.0000|\n|prev_stop_sched_hour_group15_17                         |   0.4389|    0.0155|     28.26|  0.0000|\n|prev_stop_sched_hour_group5_8                           |   0.4243|    0.0156|     27.17|  0.0000|\n|prev_stop_sched_hour_group9_11                          |  -0.2685|    0.0156|    -17.24|  0.0000|\n|route_idER                                              |  -0.2424|    0.0112|    -21.65|  0.0000|\n|schedule_seasonSUMMER_1                                 |  -0.2001|    0.0156|    -12.83|  0.0000|\n|schedule_seasonSUMMER_2                                 |   0.1921|    0.0166|     11.54|  0.0000|\n|prev_stop_sched_hour_group18_22                         |  -0.1628|    0.0152|    -10.71|  0.0000|\n|env_battery_water_level_obs                             |  -0.1483|    0.0080|    -18.61|  0.0000|\n|prev_stop_sched_hour_group18_22:schedule_daytypeWEEKEND |  -0.1227|    0.0252|     -4.88|  0.0000|\n|prev_stop_sched_hour_group9_11:schedule_daytypeWEEKEND  |   0.0883|    0.0265|      3.34|  0.0009|\n|schedule_seasonSPRING                                   |  -0.0846|    0.0152|     -5.56|  0.0000|\n|prev_stop_sched_hour_group15_17:schedule_daytypeWEEKEND |   0.0525|    0.0255|      2.06|  0.0397|\n|env_temperature_c                                       |   0.0284|    0.0008|     36.36|  0.0000|\n|route_idSB                                              |  -0.0190|    0.0127|     -1.50|  0.1334|\n|env_wind_speed_mps                                      |   0.0180|    0.0017|     10.65|  0.0000|\n|env_precipitation_mm                                    |  -0.0157|    0.0023|     -6.83|  0.0000|\n|schedule_daytypeWEEKEND                                 |  -0.0123|    0.0184|     -0.67|  0.5026|\n|schedule_seasonWINTER                                   |  -0.0016|    0.0169|     -0.10|  0.9231|\n\n\n:::\n:::\n\n\n#### Supporting Exploratory Patterns\n\nThe following exploratory plots provide visual context for the coefficient interpretation. They show how delay accumulates, how lateness varies across time bins and day type, and how selected environmental and route-level patterns relate to average lateness.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble::tibble(\n  component = factor(\n    c(\"Inherited previous delay\", \"Carried within-trip delay\", \"New delay at current stop\"),\n    levels = c(\"Inherited previous delay\", \"Carried within-trip delay\", \"New delay at current stop\")\n  ),\n  minutes = c(6.24, 1.85, 1.68)\n) %>%\n  ggplot(aes(x = \"Excessive delay example\", y = minutes, fill = component)) +\n  geom_col(width = 0.45) +\n  geom_text(aes(label = paste0(minutes, \" min\")),\n            position = position_stack(vjust = 0.5),\n            color = \"white\", fontface = \"bold\", size = 4) +\n  scale_fill_manual(values = c(\n    \"Inherited previous delay\"   = \"#EB5600\",\n    \"Carried within-trip delay\"  = \"#1A9988\",\n    \"New delay at current stop\"  = \"#C7C7C7\"\n  )) +\n  labs(title    = \"Where Does Excessive Delay Come From?\",\n       subtitle = \"Most excessive delay is inherited or carried forward, not newly created at the current stop\",\n       x = NULL, y = \"Minutes of delay\", fill = NULL) +\n  theme_minimal(base_size = 12) +\n  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),\n        panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(),\n        legend.position = \"bottom\", plot.title = element_text(face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/ming-delay-components-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_model %>%\n  group_by(route_id, stop_sequence) %>%\n  summarise(avg_lateness = mean(.data[[outcome_cont]], na.rm = TRUE), n = n(), .groups = \"drop\") %>%\n  filter(n >= 100) %>%\n  ggplot(aes(x = stop_sequence, y = avg_lateness, color = route_id)) +\n  geom_line(linewidth = 0.9) +\n  geom_point(size = 1.8) +\n  labs(title    = \"Delay Accumulation Along Route\",\n       subtitle = \"Average lateness tends to change as trips move through stop sequence\",\n       x = \"Stop sequence\", y = \"Average lateness (minutes)\", color = \"Route\") +\n  theme_minimal(base_size = 12) +\n  theme(plot.title = element_text(face = \"bold\"), legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/ming-delay-accumulation-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlateness_col <- c(outcome_cont, \"arr_lateness\", \"arr_late_min\", \"arrival_lateness\",\n                  \"delay_min\", \"lateness\")[\n  c(outcome_cont, \"arr_lateness\", \"arr_late_min\", \"arrival_lateness\",\n    \"delay_min\", \"lateness\") %in% names(df_model)][1]\n\nif (is.na(lateness_col)) stop(\"Could not find the lateness column.\")\n\ntime_delay_summary <- df_model %>%\n  mutate(lateness_for_plot = .data[[lateness_col]]) %>%\n  filter(!is.na(prev_stop_sched_hour_group), !is.na(schedule_daytype), !is.na(lateness_for_plot)) %>%\n  group_by(prev_stop_sched_hour_group, schedule_daytype) %>%\n  summarise(avg_lateness = mean(lateness_for_plot, na.rm = TRUE), n = n(), .groups = \"drop\") %>%\n  mutate(prev_stop_sched_hour_group = factor(\n    prev_stop_sched_hour_group, levels = c(\"5_8\", \"9_11\", \"12_14\", \"15_17\", \"18_22\")\n  ))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(time_delay_summary, aes(x = prev_stop_sched_hour_group, y = avg_lateness, fill = schedule_daytype)) +\n  geom_col(position = position_dodge(width = 0.75), width = 0.6) +\n  scale_fill_manual(values = c(\"WEEKDAY\" = \"#EB5600\", \"WEEKEND\" = \"#1A9988\")) +\n  labs(title = \"Average Lateness by Time Bin and Day Type\",\n       x = \"Scheduled time bin\", y = \"Average lateness (minutes)\", fill = \"Day type\") +\n  theme_minimal(base_size = 12) +\n  theme(plot.title = element_text(face = \"bold\"), legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/ming-time-of-day-plot-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntemp_delay_summary <- df_model %>%\n  filter(!is.na(env_temperature_c), !is.na(.data[[outcome_cont]])) %>%\n  mutate(temp_bin = cut(env_temperature_c,\n                        breaks = quantile(env_temperature_c, probs = seq(0, 1, 0.1), na.rm = TRUE),\n                        include.lowest = TRUE)) %>%\n  group_by(temp_bin) %>%\n  summarise(avg_temperature = mean(env_temperature_c, na.rm = TRUE),\n            avg_lateness    = mean(.data[[outcome_cont]], na.rm = TRUE),\n            n = n(), .groups = \"drop\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(temp_delay_summary, aes(x = avg_temperature, y = avg_lateness)) +\n  geom_point(color = \"#1A9988\", size = 2.5) +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"#EB5600\") +\n  labs(title = \"Temperature and Average Lateness\",\n       x = \"Average temperature (°C)\", y = \"Average lateness (minutes)\") +\n  theme_minimal(base_size = 12) +\n  theme(plot.title = element_text(face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/ming-temperature-plot-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (\"expected_water_min\" %in% names(df_model)) {\n  df_model %>%\n    group_by(route_id) %>%\n    summarise(avg_delay              = mean(.data[[outcome_cont]], na.rm = TRUE),\n              avg_expected_water_min = mean(expected_water_min, na.rm = TRUE),\n              n = n(), .groups = \"drop\") %>%\n    ggplot(aes(x = avg_expected_water_min, y = avg_delay, label = route_id)) +\n    geom_point(size = 3) +\n    geom_text(nudge_y = 0.15) +\n    geom_smooth(method = \"lm\", se = FALSE) +\n    labs(title = \"Route Travel Time vs Average Lateness\",\n         x = \"Average expected water travel time (minutes)\\n(proxy for route length / exposure)\",\n         y = \"Average lateness (minutes)\") +\n    theme_minimal()\n}\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/ming-route-travel-time-plot-1.png){width=768}\n:::\n:::\n\n\n#### Monitorable Signals Beyond Prior Delay\n\nAlthough operational propagation explains the largest share of delay variation, smaller signals are still useful when they are monitorable. Environmental conditions, time patterns, and vessel/load context may not dominate the model, but they describe conditions that operators can check before or during service.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndomain_e_plot_predictors <- intersect(c(\n  domain_e_predictors, \"prev_stop_boardings\", \"prev_stop_alightings\",\n  \"prev_stop_onboard\", \"prev_stop_load_factor\"\n), names(df_model))\n\nbce_predictors       <- unique(c(domain_b_predictors, domain_c_predictors, domain_e_plot_predictors))\nplot_model_predictors <- unique(c(domain_a_predictors, domain_b_predictors, domain_c_predictors,\n                                   domain_d_predictors, domain_e_plot_predictors))\nnumeric_predictors   <- plot_model_predictors[sapply(df_model[plot_model_predictors], is.numeric)]\n\ndf_model_std <- df_model %>%\n  mutate(across(all_of(numeric_predictors), ~ as.numeric(scale(.x))))\n\ncombined_std_fit <- lm(\n  as.formula(paste(outcome_cont, \"~\", paste(plot_model_predictors, collapse = \" + \"))),\n  data = df_model_std\n)\n\nlabel_lookup <- c(\n  env_temperature_c              = \"Temperature\",\n  env_wind_speed_mps             = \"Wind speed\",\n  env_visibility_m               = \"Visibility\",\n  env_precipitation_mm           = \"Precipitation\",\n  env_battery_water_level_obs    = \"Water level\",\n  env_battery_water_level_anomaly = \"Water-level anomaly\",\n  env_narrows_current_obs        = \"Current\",\n  env_narrows_current_residual   = \"Current residual\",\n  prev_stop_sched_hour           = \"Previous scheduled hour\",\n  prev_stop_sched_hour_group     = \"Previous scheduled hour group\",\n  schedule_season                = \"Schedule season\",\n  schedule_daytype               = \"Schedule day type\",\n  vessel_capacity                = \"Vessel capacity\",\n  vessel_trip_seq_in_chain       = \"Vessel trip sequence\",\n  prev_stop_boardings            = \"Boardings\",\n  prev_stop_alightings           = \"Alightings\",\n  prev_stop_onboard              = \"Onboard count\",\n  prev_stop_load_factor          = \"Load factor\"\n)\n\nget_base_var <- function(term, vars) {\n  hits <- vars[vapply(vars, function(v) startsWith(term, v), logical(1))]\n  if (length(hits) == 0) return(NA_character_)\n  hits[which.max(nchar(hits))]\n}\n\ncoef_plot_df <- broom::tidy(combined_std_fit) %>%\n  filter(term != \"(Intercept)\") %>%\n  rowwise() %>%\n  mutate(variable = get_base_var(term, bce_predictors)) %>%\n  ungroup() %>%\n  filter(!is.na(variable)) %>%\n  mutate(\n    domain = case_when(\n      variable %in% domain_b_predictors       ~ \"Environmental Conditions\",\n      variable %in% domain_c_predictors       ~ \"Temporal Patterns\",\n      variable %in% domain_e_plot_predictors  ~ \"Demand and Vessel Context\",\n      TRUE ~ \"Other\"\n    )\n  ) %>%\n  filter(domain != \"Other\",\n         !str_detect(term, \"^schedule_season\"),\n         !variable %in% c(\"prev_stop_load_factor\", \"prev_stop_onboard\", \"vessel_trip_seq_in_chain\")) %>%\n  mutate(\n    clean_label = if_else(\n      variable %in% names(label_lookup),\n      unname(label_lookup[variable]),\n      variable\n    ),\n    clean_label = case_when(\n      variable == \"schedule_daytype\"           ~ str_replace(term, variable, \"Schedule day type \"),\n      variable == \"prev_stop_sched_hour_group\" ~ str_replace(term, variable, \"Previous scheduled hour \"),\n      TRUE ~ clean_label\n    ),\n    abs_estimate = abs(estimate)\n  )\n\ncoef_plot_top <- bind_rows(\n  coef_plot_df %>% filter(domain == \"Environmental Conditions\") %>% slice_max(abs_estimate, n = 4, with_ties = FALSE),\n  coef_plot_df %>% filter(domain == \"Temporal Patterns\")        %>% slice_max(abs_estimate, n = 3, with_ties = FALSE),\n  coef_plot_df %>% filter(domain == \"Demand and Vessel Context\") %>% slice_max(abs_estimate, n = 4, with_ties = FALSE)\n) %>%\n  distinct(term, .keep_all = TRUE) %>%\n  arrange(abs_estimate)\n\nggplot(coef_plot_top, aes(x = reorder(clean_label, abs_estimate), y = abs_estimate, fill = domain)) +\n  geom_col(width = 0.72) +\n  coord_flip() +\n  scale_fill_manual(values = c(\n    \"Environmental Conditions\"  = \"#1A9988\",\n    \"Temporal Patterns\"         = \"#7A7A7A\",\n    \"Demand and Vessel Context\" = \"#EB5600\"\n  )) +\n  labs(title = \"Monitorable Signals Beyond Prior Delay\",\n       x = NULL, y = \"Absolute standardized coefficient\", fill = NULL) +\n  theme_minimal(base_size = 12) +\n  theme(legend.position = \"bottom\", panel.grid.major.y = element_blank(),\n        plot.title = element_text(face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/ming-monitorable-signals-1.png){width=768}\n:::\n:::\n\n\n#### Operational Interpretation\n\nThe focused coefficient results and supporting plots reinforce three operational takeaways.\n\nFirst, prior delay remains the strongest signal. This means delay management needs to account for accumulation across stops and linked trips, not only conditions at the current stop.\n\nSecond, route and stop structure matter. Some parts of the system appear to have a less favorable baseline, meaning they may be more vulnerable to delay even before short-run conditions are considered.\n\nThird, weather, water, time, and vessel/load patterns are smaller signals, but they are monitorable. They can help operators understand when conditions may be less favorable and where extra attention may be useful.\n\n## Predictive Model\n**By: Guangze 'Simon' Sun**\n\n### Feature Table Construction\n\nThe prediction feature table consolidates schedule structure, stop context, lagged demand, vessel traffic (AIS), and environmental conditions into a single modeling dataset. Each row represents one stop-level trip observation. The table below lists the required predictors; the build chunk is set to `eval: false` since it writes output files and depends on the full source parquet.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsource_parquet <- \"../exploratory_code/modeling/baseline_prediction_table_stop_level_v2.parquet\"\nout_csv     <- \"../exploratory_code/modeling/final_predictive_feature_table.csv\"\nout_parquet <- \"../exploratory_code/modeling/final_predictive_feature_table.parquet\"\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfeature_table <- arrow::read_parquet(source_parquet) %>% as_tibble()\n\nrequired_predictors <- c(\n  \"alightings_lag_7d\", \"boardings_lag_7d\", \"curr_stop_shared_stop_flag\",\n  \"curr_vessel_count_lag_7d\", \"direction\", \"expected_water_min\",\n  \"is_terminal_stop\", \"planned_turnaround_gap_min\", \"prev_stop_sched_hour\",\n  \"prev_stop_shared_stop_flag\", \"prev_vessel_count_lag_7d\", \"schedule_daytype\",\n  \"schedule_season\", \"scheduled_headway_min\", \"stop_sequence\", \"vessel_capacity\",\n  \"vessel_trip_seq_in_chain\", \"env_battery_water_level_obs\", \"env_narrows_current_obs\",\n  \"env_precipitation_mm\", \"env_temperature_c\", \"env_visibility_m\",\n  \"env_wind_speed_mps\", \"from_stop_id\", \"to_stop_id\", \"segment_hourly_vessel_count_all\"\n)\n\nrequired_columns <- c(\"trip_date\", \"lateness_vs_original_schedule_min\", required_predictors)\nmissing_columns  <- setdiff(required_columns, names(feature_table))\nif (length(missing_columns) > 0) stop(\"Missing required columns: \", paste(missing_columns, collapse = \", \"))\nstopifnot(nrow(feature_table) > 0)\nstopifnot(anyDuplicated(names(feature_table)) == 0)\nstopifnot(\"segment_hourly_vessel_count_all\" %in% names(feature_table))\nstopifnot(\"prev_stop_sched_hour\" %in% names(feature_table))\n\nreadr::write_csv(feature_table, out_csv)\narrow::write_parquet(feature_table, out_parquet)\nstopifnot(file.exists(out_csv), file.exists(out_parquet))\n```\n:::\n\n\n### Baseline Model-Family Comparison\n\nWe used a chronological train / validation / test split. The most recent 30 days were held out as the test set, the previous 30 days were used as validation, and earlier observations were used for training. This matches the operational setting where future trips are predicted from historical data.\n\nThe baseline screen compared five model families: Logistic Regression, SVM, DNN, Random Forest, and XGBoost. SVM used a capped 20,000-row stratified training sample, so it should be interpreted as lightweight screening evidence. The baseline screen supported carrying forward Random Forest and XGBoost for focused finalist comparison.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_dir <- \"../exploratory_code/modeling\"\n\nbaseline_file   <- file.path(model_dir, \"baseline_model_family_comparison.csv\")\nprediction_file <- file.path(model_dir, \"final_rf_xgb_test_predictions.csv\")\nimportance_file <- file.path(model_dir, \"final_rf_top10_feature_importance.csv\")\n\nthreshold_source_note <- \"Test predictions were used for the recall >= 0.20 operating-point table because validation prediction probabilities were not available in the final delivery package.\"\nrf_xgb_highlight_note <- \"Yellow shading marks recall ranges where RF has higher precision than XGBoost and at least one model has precision >= 0.10.\"\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!file.exists(baseline_file)) {\n  warning(\"Missing baseline comparison file: \", baseline_file)\n} else {\n  baseline_tbl <- read_csv(baseline_file, show_col_types = FALSE) %>%\n    mutate(model_family = fct_reorder(model_family, validation_roc_auc))\n\n  ggplot(baseline_tbl, aes(x = validation_roc_auc, y = model_family)) +\n    geom_col(fill = \"#1A9988\", width = 0.68) +\n    scale_x_continuous(labels = percent_format(accuracy = 1), limits = c(0, NA)) +\n    labs(title = \"Baseline Model-Family Screen\", x = \"Validation ROC-AUC\", y = NULL) +\n    theme_minimal(base_size = 15) +\n    theme(plot.title = element_text(face = \"bold\", size = 18), panel.grid.minor = element_blank())\n}\n```\n:::\n\n\n### Final RF vs XGBoost Comparison\n\nAfter the baseline screen, we focused on Random Forest and XGBoost. Both model families can capture nonlinear relationships and interactions among schedule structure, stop context, lagged demand, vessel traffic, and environmental conditions.\n\nThe final tuning process used `trees = 1500` as the practical central setting. Around that tree count, RF tuning mainly adjusted `mtry` and `min_n`. XGBoost tuning adjusted tree depth, `min_n`, learning rate, loss reduction, and feature sampling. The final comparison retained one RF operational candidate and one XGBoost benchmark candidate.\n\nXGBoost remains a strong predictive benchmark, but the dashboard use case emphasizes conservative alerting rather than global ranking alone. In the higher-precision region, Random Forest provides a more useful recall balance, so we select RF as the operational model and retain XGBoost as the benchmark.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!file.exists(prediction_file)) {\n  warning(\"Missing final RF/XGB prediction file: \", prediction_file)\n} else {\n  pred_tbl <- read_csv(prediction_file, show_col_types = FALSE) %>%\n    mutate(delay_gt_10 = factor(delay_gt_10, levels = c(\"no\", \"yes\")))\n\n  pr_tbl <- bind_rows(\n    pred_tbl %>% transmute(model = \"Final RF\",  delay_gt_10, .pred_yes = rf_pred_yes)  %>%\n      group_by(model) %>% pr_curve(truth = delay_gt_10, .pred_yes, event_level = \"second\"),\n    pred_tbl %>% transmute(model = \"Final XGB\", delay_gt_10, .pred_yes = xgb_pred_yes) %>%\n      group_by(model) %>% pr_curve(truth = delay_gt_10, .pred_yes, event_level = \"second\")\n  )\n\n  prep_curve <- function(dat, model_name) {\n    dat %>%\n      filter(model == model_name, is.finite(recall), is.finite(precision)) %>%\n      group_by(recall) %>%\n      summarise(precision = max(precision, na.rm = TRUE), .groups = \"drop\") %>%\n      arrange(recall)\n  }\n\n  interp_precision <- function(curve, recall_grid) {\n    approx(curve$recall, curve$precision, xout = recall_grid, rule = 2, ties = \"ordered\")$y\n  }\n\n  rf_curve  <- prep_curve(pr_tbl, \"Final RF\")\n  xgb_curve <- prep_curve(pr_tbl, \"Final XGB\")\n  max_shared_recall <- min(max(rf_curve$recall, na.rm = TRUE), max(xgb_curve$recall, na.rm = TRUE))\n  recall_grid <- seq(0, max_shared_recall, length.out = 600)\n\n  highlight_grid <- tibble(\n    recall        = recall_grid,\n    rf_precision  = interp_precision(rf_curve,  recall_grid),\n    xgb_precision = interp_precision(xgb_curve, recall_grid)\n  ) %>%\n    mutate(\n      high_precision_region = pmax(rf_precision, xgb_precision, na.rm = TRUE) >= 0.10,\n      rf_above_xgb = rf_precision > xgb_precision,\n      highlight    = rf_above_xgb & high_precision_region\n    )\n\n  if (!any(highlight_grid$highlight, na.rm = TRUE)) {\n    highlight_grid <- highlight_grid %>% mutate(highlight = rf_above_xgb)\n    rf_xgb_highlight_note <- \"No RF-above-XGB intervals met the precision >= 0.10 rule, so the plot highlights all recall ranges where RF precision is above XGBoost.\"\n  }\n\n  highlight_intervals <- highlight_grid %>%\n    mutate(run_id = cumsum(highlight != lag(highlight, default = first(highlight)))) %>%\n    filter(highlight) %>%\n    group_by(run_id) %>%\n    summarise(xmin = min(recall), xmax = max(recall), .groups = \"drop\") %>%\n    filter(xmax > xmin)\n\n  ggplot(pr_tbl, aes(x = recall, y = precision, color = model)) +\n    geom_rect(data = highlight_intervals,\n              aes(xmin = xmin, xmax = xmax, ymin = 0, ymax = 1),\n              inherit.aes = FALSE, fill = \"#F2E8CF\", alpha = 0.55) +\n    geom_path(linewidth = 1.15) +\n    scale_color_manual(values = c(\"Final RF\" = \"#D95F59\", \"Final XGB\" = \"#1A9988\")) +\n    scale_x_continuous(labels = percent_format(accuracy = 1), limits = c(0, 1)) +\n    scale_y_continuous(labels = percent_format(accuracy = 1), limits = c(0, NA)) +\n    labs(title = \"Final RF vs XGBoost Precision-Recall Curve\",\n         x = \"Recall\", y = \"Precision\", color = NULL) +\n    theme_minimal(base_size = 15) +\n    theme(plot.title = element_text(face = \"bold\", size = 18),\n          panel.grid.minor = element_blank(), legend.position = \"bottom\")\n}\n```\n:::\n\n\n### Final RF Feature Importance\n\nWe inspected feature importance from the final Random Forest model to understand what types of advance-available information the operational model relies on. This importance is model-based and descriptive; it is not a causal estimate.\n\nThe top features combine environmental / water-condition variables and recurring operational patterns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (!file.exists(importance_file)) {\n  warning(\"Missing RF feature importance file: \", importance_file)\n} else {\n  importance_tbl <- read_csv(importance_file, show_col_types = FALSE) %>%\n    arrange(desc(importance)) %>%\n    slice_head(n = 10) %>%\n    mutate(\n      display_label = dplyr::recode(\n        feature,\n        segment_hourly_vessel_count_all  = \"Segment vessel count, 7-day lag\",\n        boardings_lag_7d                 = \"Boardings, 7-day lag\",\n        alightings_lag_7d                = \"Alightings, 7-day lag\",\n        curr_vessel_count_lag_7d         = \"Current-stop vessel count, 7-day lag\",\n        prev_vessel_count_lag_7d         = \"Previous-stop vessel count, 7-day lag\",\n        env_temperature_c                = \"Temperature\",\n        env_battery_water_level_obs      = \"Battery water level\",\n        env_narrows_current_obs          = \"Narrows current\",\n        env_precipitation_mm             = \"Precipitation\",\n        env_visibility_m                 = \"Visibility\",\n        env_wind_speed_mps               = \"Wind speed\",\n        expected_water_min               = \"Expected water time\",\n        planned_turnaround_gap_min       = \"Planned turnaround gap\",\n        prev_stop_sched_hour             = \"Scheduled hour\",\n        .default = str_to_sentence(str_replace_all(feature, \"_\", \" \"))\n      )\n    )\n\n  ggplot(importance_tbl, aes(x = importance, y = fct_reorder(display_label, importance))) +\n    geom_col(fill = \"#1A9988\", width = 0.72) +\n    labs(title = \"Final RF Feature Importance\", x = \"Importance\", y = NULL) +\n    theme_minimal(base_size = 15) +\n    theme(plot.title = element_text(face = \"bold\", size = 18), panel.grid.minor = element_blank())\n}\n```\n\n::: {.cell-output-display}\n![](technical-report_files/figure-html/simon-feature-importance-1.png){width=672}\n:::\n:::\n\n\nThe final RF relies on a mix of environmental conditions, water-current context, and recurring operational demand/vessel-pattern features.\n\n# Interpretation and Implications\n\n\n\n\n# Acknowledgements\n\n\n\n\n# Code Appendix\nThrough this project process, we wrote a lot of code that is not meaningful toward our final results. You can view that below.\n\n\n# References",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}